/* Asset inventory: a table in the browser, CSV in and out, warranty and age at a glance. */
(function(){"use strict";
var $=function(i){return document.getElementById(i)};var out=$("as-table");if(!out)return;
function esc(s){return String(s===undefined||s===null?"":s).replace(/[&<>"]/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]})}
var COLS=[["tag","Tag"],["kind","Kind"],["model","Make and model"],["serial","Serial number"],["user","User"],["place","Location"],["bought","Bought"],["warranty","Warranty until"],["price","Price"],["note","Note"]];
var KINDS=["Notebook","Desktop","Monitor","Server","Switch","Firewall","Access point","Printer","Phone","Tablet","NAS","UPS","Dock","Other"];
var ALIAS={tag:/^(tag|asset|asset ?tag|inventory|inventar|id|nr|nummer|number)/i,kind:/^(kind|type|typ|art|category|kategorie)/i,model:/^(model|modell|make|device|ger[aä]t|name|bezeichnung|hersteller)/i,serial:/^(serial|sn|s\/n|serien)/i,user:/^(user|owner|benutzer|nutzer|assigned|mitarbeiter)/i,place:/^(place|location|standort|ort|room|raum|site)/i,bought:/^(bought|purchase|kauf|gekauft|date|datum|anschaff)/i,warranty:/^(warranty|garantie|gew[aä]hr)/i,price:/^(price|preis|cost|kosten|value|wert)/i,note:/^(note|notiz|comment|bemerk|kommentar)/i};
var KEY="ah_assets",ONKEY="ah_assets_on",rows=[],sortBy="tag",asc=true,editing=null,today=new Date();today.setHours(0,0,0,0);
function isOn(){try{return localStorage.getItem(ONKEY)==="1"}catch(e){return false}}
function save(){try{if(isOn())localStorage.setItem(KEY,JSON.stringify(rows))}catch(e){status("The browser would not store the list. Export it as CSV to keep it.")}}
function status(t){$("as-status").textContent=t}
function date(s){s=String(s||"").trim();var m=/^(\d{4})-(\d{1,2})(?:-(\d{1,2}))?/.exec(s);if(m)return iso(+m[1],+m[2],+(m[3]||1));m=/^(\d{1,2})\.(\d{1,2})\.(\d{2,4})$/.exec(s);if(m)return iso(+m[3]<100?2000+ +m[3]:+m[3],+m[2],+m[1]);m=/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/.exec(s);if(m)return iso(+m[3],+m[1],+m[2]);return ""}
function iso(y,m,d){if(y<1990||y>2100||m<1||m>12||d<1||d>31)return "";return y+"-"+("0"+m).slice(-2)+"-"+("0"+d).slice(-2)}
function days(s){if(!s)return null;var p=s.split("-"),d=new Date(+p[0],+p[1]-1,+p[2]);return Math.round((d-today)/864e5)}
function money(s){var t=String(s||"").replace(/[^\d.,-]/g,"");if(!t)return "";if(/,\d{1,2}$/.test(t))t=t.replace(/\./g,"").replace(",",".");else t=t.replace(/,/g,"");var n=parseFloat(t);return isNaN(n)?"":String(Math.round(n*100)/100)}
function clean(o){var r={};COLS.forEach(function(c){r[c[0]]=String(o[c[0]]===undefined?"":o[c[0]]).trim().slice(0,120)});r.bought=date(r.bought);r.warranty=date(r.warranty);r.price=money(r.price);return r}
function parseCsv(text){var rowsOut=[],row=[],cur="",q=false,i,c,first=text.split(/\r?\n/)[0]||"",d=(first.match(/;/g)||[]).length>(first.match(/,/g)||[]).length?";":(first.match(/\t/g)||[]).length>(first.match(/,/g)||[]).length?"\t":",";
  text=text.replace(/^﻿/,"");for(i=0;i<text.length;i++){c=text[i];
    if(q){if(c==='"'){if(text[i+1]==='"'){cur+='"';i++}else q=false}else cur+=c;continue}
    if(c==='"'&&cur===""){q=true;continue}if(c===d){row.push(cur);cur="";continue}
    if(c==="\n"||c==="\r"){if(c==="\r"&&text[i+1]==="\n")i++;row.push(cur);cur="";if(row.some(function(x){return x.trim()!==""}))rowsOut.push(row);row=[];continue}cur+=c}
  row.push(cur);if(row.some(function(x){return x.trim()!==""}))rowsOut.push(row);return rowsOut}
function importCsv(text){var t=parseCsv(text);if(t.length<2)return{n:0,err:"No rows found. The first line must hold the column names."};var head=t[0],map={},unknown=[];
  head.forEach(function(h,i){var k=null;COLS.forEach(function(c){if(k===null&&map[c[0]]===undefined&&ALIAS[c[0]].test(h.trim()))k=c[0]});if(k!==null)map[k]=i;else if(h.trim())unknown.push(h.trim())});
  if(map.tag===undefined&&map.model===undefined&&map.serial===undefined)return{n:0,err:"None of the columns looks like a tag, a model or a serial number. Name the columns like the ones in the export."};
  var n=0,seen={};rows.forEach(function(r){seen[r.tag]=1});t.slice(1,5001).forEach(function(line){var o={};Object.keys(map).forEach(function(k){o[k]=line[map[k]]});o=clean(o);if(!o.tag)o.tag=nextTag();if(seen[o.tag]){var old=rows.filter(function(r){return r.tag===o.tag})[0];Object.keys(o).forEach(function(k){if(o[k])old[k]=o[k]})}else{rows.push(o);seen[o.tag]=1}n++});
  return{n:n,unknown:unknown}}
function csvCell(s){s=String(s);if(/^[=+\-@\t\r]/.test(s))s="'"+s;return /[",;\n]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s}
function toCsv(){return COLS.map(function(c){return csvCell(c[1])}).join(",")+"\r\n"+rows.map(function(r){return COLS.map(function(c){return csvCell(r[c[0]])}).join(",")}).join("\r\n")+"\r\n"}
function nextTag(){var max=0,pre="IT-",w=4;rows.forEach(function(r){var m=/^(.*?)(\d+)$/.exec(r.tag);if(m&&+m[2]>=max){max=+m[2];pre=m[1];w=m[2].length}});var n=String(max+1);while(n.length<w)n="0"+n;return pre+n}
function state(r){var w=days(r.warranty),b=days(r.bought),age=b===null?null:-b/365.25;
  if(w!==null&&w<0)return["out","ended"];if(w!==null&&w<=90)return["soon",w+" days left"];if(age!==null&&age>=5)return["old",Math.floor(age)+" years old"];return["",""]}
function filtered(){var q=$("as-q").value.trim().toLowerCase(),only=$("as-only").value;return rows.filter(function(r){if(only&&state(r)[0]!==only)return false;if(!q)return true;return COLS.some(function(c){return r[c[0]].toLowerCase().indexOf(q)>=0})})}
function render(){var list=filtered(),num=sortBy==="price";list.sort(function(a,b){var x=a[sortBy],y=b[sortBy];if(num){x=+x||0;y=+y||0}else{x=x.toLowerCase();y=y.toLowerCase()}return (x<y?-1:x>y?1:0)*(asc?1:-1)});
  var exp=0,soon=0,old=0,val=0,byKind={};rows.forEach(function(r){var s=state(r)[0];if(s==="out")exp++;if(s==="soon")soon++;var b=days(r.bought);if(b!==null&&-b/365.25>=5){old++;byKind[r.kind||"Other"]=(byKind[r.kind||"Other"]||0)+(+r.price||0)}val+=+r.price||0});
  var h='<div class="stats"><div class="stat"><span class="stat-k">devices</span><b class="stat-v" data-raw="1">'+rows.length+'</b><span class="stat-s">bought for '+Math.round(val).toLocaleString("en-US")+'</span></div><div class="stat"><span class="stat-k">out of warranty</span><b class="stat-v" data-raw="1">'+exp+'</b></div><div class="stat"><span class="stat-k">warranty ends within 90 days</span><b class="stat-v" data-raw="1">'+soon+'</b></div><div class="stat"><span class="stat-k">five years and older</span><b class="stat-v" data-raw="1">'+old+'</b><span class="stat-s">'+(old?"about "+Math.round(Object.keys(byKind).reduce(function(t,k){return t+byKind[k]},0)).toLocaleString("en-US")+" to replace at old prices":"nothing due")+'</span></div></div>';
  $("as-stats").innerHTML=h;
  if(!rows.length){out.innerHTML='<p class="dim">The list is empty. Add a device, import a CSV file, or load the example to see how it looks.</p>';return}
  h='<p class="dim asmeta">'+list.length+' of '+rows.length+' shown. Click a tag to edit the device.</p><div class="tw"><table class="tbl astbl"><thead><tr>'+COLS.map(function(c){return '<th scope="col" aria-sort="'+(sortBy===c[0]?(asc?"ascending":"descending"):"none")+'"><button type="button" class="assort" data-sort="'+c[0]+'">'+c[1]+(sortBy===c[0]?'<span aria-hidden="true"> '+(asc?"▲":"▼")+'</span>':'')+'</button></th>'}).join("")+'</tr></thead><tbody>';
  list.forEach(function(r){var s=state(r),i=rows.indexOf(r);h+='<tr'+(s[0]?' class="as-'+s[0]+'"':'')+'>'+COLS.map(function(c){var x=r[c[0]];return '<td'+(c[0]==="price"?' class="num"':'')+'>'+(c[0]==="tag"?'<button type="button" class="astag" data-edit="'+i+'" aria-label="Edit '+esc(x)+'">'+esc(x)+'</button>':c[0]==="serial"?'<code>'+esc(x)+'</code>':c[0]==="price"&&x?Number(x).toLocaleString("en-US"):c[0]==="bought"||c[0]==="warranty"?'<span class="asd">'+esc(x)+'</span>':esc(x))+(s[0]&&c[0]===(s[0]==="old"?"bought":"warranty")?' <span class="sevtag s-'+({out:"high",soon:"med",old:"info"})[s[0]]+'">'+s[1]+'</span>':'')+'</td>'}).join("")+'</tr>'});
  out.innerHTML=h+'</tbody></table></div>'}
function fillForm(r){COLS.forEach(function(c){$("as-f-"+c[0]).value=r?r[c[0]]:""});if(!r){$("as-f-tag").value=nextTag();$("as-f-kind").value="Notebook"}
  $("as-form-t").textContent=r?"Edit "+r.tag:"Add a device";$("as-del").hidden=!r;$("as-save").textContent=r?"Save the changes":"Add to the list"}
function openForm(i){editing=i;fillForm(i===null?null:rows[i]);$("as-form").hidden=false;$("as-f-"+(i===null?"model":"tag")).focus();$("as-form").scrollIntoView({block:"nearest"})}
/* form fields */
(function(){var h="";COLS.forEach(function(c){var id="as-f-"+c[0];if(c[0]==="kind")h+='<label>'+c[1]+'<select class="sel" id="'+id+'">'+KINDS.map(function(k){return "<option>"+k+"</option>"}).join("")+'</select></label>';
  else h+='<label>'+c[1]+'<input class="sel" id="'+id+'" maxlength="120" autocomplete="off"'+(c[0]==="bought"||c[0]==="warranty"?' type="date"':c[0]==="price"?' type="text" inputmode="decimal"':' type="text"')+(c[0]==="serial"||c[0]==="tag"?' spellcheck="false"':'')+'></label>'});$("as-fields").innerHTML=h})();
$("as-add").addEventListener("click",function(){openForm(null)});
$("as-cancel").addEventListener("click",function(){$("as-form").hidden=true;$("as-add").focus()});
$("as-form").addEventListener("submit",function(e){e.preventDefault();var o={};COLS.forEach(function(c){o[c[0]]=$("as-f-"+c[0]).value});o=clean(o);if(!o.tag)o.tag=nextTag();
  var clash=rows.filter(function(r,i){return r.tag===o.tag&&i!==editing})[0];if(clash){status("The tag "+o.tag+" is already used by "+(clash.model||"another device")+". Tags must be unique.");$("as-f-tag").focus();return}
  if(editing===null)rows.push(o);else rows[editing]=o;dirty=true;save();$("as-form").hidden=true;status((editing===null?"Added ":"Saved ")+o.tag+".");render();$("as-add").focus()});
$("as-del").addEventListener("click",function(){if(editing===null)return;var t=rows[editing].tag;if(!window.confirm("Delete "+t+" from the list?"))return;rows.splice(editing,1);save();$("as-form").hidden=true;status("Deleted "+t+".");render();$("as-add").focus()});
out.addEventListener("click",function(e){var b=e.target.closest("[data-sort]"),ed=e.target.closest("[data-edit]");if(b){var k=b.getAttribute("data-sort");if(sortBy===k)asc=!asc;else{sortBy=k;asc=true}render();var nb=out.querySelector('[data-sort="'+k+'"]');if(nb)nb.focus()}else if(ed)openForm(+ed.getAttribute("data-edit"))});
$("as-q").addEventListener("input",render);$("as-only").addEventListener("change",render);
function doImport(text){var r=importCsv(text);if(r.err){status(r.err);return}dirty=true;save();render();status(r.n+" rows read."+(r.unknown&&r.unknown.length?" Columns not used: "+r.unknown.join(", ")+".":""))}
$("as-file").addEventListener("change",function(){var f=this.files&&this.files[0];if(!f)return;if(f.size>5e6){status("The file is larger than 5 MB. That is not an inventory list.");return}var rd=new FileReader();rd.onload=function(){doImport(String(rd.result))};rd.readAsText(f);this.value=""});
$("as-paste-go").addEventListener("click",function(){var t=$("as-paste").value;if(!t.trim()){status("Paste the rows first, with the column names in the first line.");return}doImport(t);$("as-paste").value=""});
$("as-export").addEventListener("click",function(){if(!rows.length){status("Nothing to export yet.");return}var a=document.createElement("a");a.href="data:text/csv;charset=utf-8,"+encodeURIComponent("﻿"+toCsv());a.download="asset-inventory-"+iso(today.getFullYear(),today.getMonth()+1,today.getDate())+".csv";document.body.appendChild(a);a.click();setTimeout(function(){document.body.removeChild(a)},100);status("Exported "+rows.length+" rows as CSV. Excel and LibreOffice open it directly.")});
$("as-print").addEventListener("click",function(){window.print()});
$("as-sample").addEventListener("click",function(){if(rows.length&&!window.confirm("Add 12 example devices to the list?"))return;var y=today.getFullYear();
  [["IT-0001","Notebook","Lenovo ThinkPad T14 Gen 3","PF3EXAMPL1","Anna Example","Office 2",(y-3)+"-03-14",(y)+"-03-13","1290",""],["IT-0002","Notebook","Lenovo ThinkPad T14 Gen 5","PF5EXAMPL2","Ben Sample","Office 2",(y-1)+"-09-02",(y+2)+"-09-01","1420",""],["IT-0003","Desktop","Dell OptiPlex 7010","7XEXMP3","Reception","Front desk",(y-6)+"-05-20",(y-3)+"-05-19","780","Windows 10 only, replace"],["IT-0004","Monitor","Dell P2422H","CN0EXAMPL4","Reception","Front desk",(y-4)+"-05-20",(y-1)+"-05-19","190",""],["IT-0005","Server","HPE ProLiant DL360 Gen10","CZ2EXAMPL5","","Rack 1, U20",(y-5)+"-11-03",(y)+"-11-02","6400","Hyper-V host"],["IT-0006","Switch","Aruba 2930F 48G PoE+","SGEXAMPL06","","Rack 1, U40",(y-5)+"-11-03","","2900","lifetime warranty"],["IT-0007","Firewall","FortiGate 60F","FGT60FEXAMPL7","","Rack 1, U38",(y-2)+"-01-15",(y+1)+"-01-14","950","licence ends with the warranty"],["IT-0008","Access point","Ubiquiti U6 Pro","E4EXAMPL08","","Ceiling, office 2",(y-2)+"-06-10",(y)+"-06-09","160",""],["IT-0009","Printer","Brother HL-L6400DW","E7EXAMPL09","","Corridor",(y-7)+"-02-01",(y-4)+"-01-31","520","drum due"],["IT-0010","NAS","Synology DS923+","23EXAMPL10","","Rack 1, U10",(y-2)+"-04-22",(y+1)+"-04-21","1100","backup target"],["IT-0011","UPS","APC Smart-UPS 1500 RM","ASEXAMPL11","","Rack 1, U1",(y-5)+"-11-03",(y-2)+"-11-02","890","battery replaced "+(y-1)],["IT-0012","Phone","Apple iPhone 14","F2EXAMPL12","Anna Example","",(y-2)+"-10-05",(y-1)+"-10-04","850","supervised"]]
  .forEach(function(a){if(rows.some(function(r){return r.tag===a[0]}))return;var o={};COLS.forEach(function(c,i){o[c[0]]=a[i]});rows.push(o)});save();render();status("Example devices added. Delete them with Empty the list when you have seen enough.")});
$("as-clear").addEventListener("click",function(){if(!rows.length)return;if(!window.confirm("Remove all "+rows.length+" devices from the list? Export first if you want to keep them."))return;rows=[];save();render();status("The list is empty.")});
$("as-keep").checked=isOn();
$("as-keep").addEventListener("change",function(){try{if(this.checked){localStorage.setItem(ONKEY,"1");save();status("The list is now kept in this browser, on this device only.")}else{localStorage.removeItem(ONKEY);localStorage.removeItem(KEY);status("Stored copy deleted. The list lives until you close the tab.")}}catch(e){this.checked=false;status("This browser does not allow storing here.")}});
try{if(isOn()){var d=JSON.parse(localStorage.getItem(KEY)||"[]");if(Array.isArray(d))rows=d.slice(0,5000).map(clean)}}catch(e){}
var dirty=false;window.addEventListener("beforeunload",function(e){if(dirty&&rows.length&&!isOn()){e.preventDefault();e.returnValue=""}});
$("as-export").addEventListener("click",function(){dirty=false});
render();window.asTest={importCsv:function(t){var r=importCsv(t);render();return r},rows:function(){return rows},toCsv:toCsv};
})();
