/* Licence and subscription tracker: renewals, cost per month and year, CSV in and out. */
(function(){"use strict";
var $=function(i){return document.getElementById(i)};var out=$("lt-table");if(!out)return;
function esc(s){return String(s===undefined||s===null?"":s).replace(/[&<>"]/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]})}
var COLS=[["name","Product"],["vendor","Vendor"],["seats","Seats"],["price","Price per seat"],["cycle","Billed"],["renew","Renews on"],["notice","Notice, days"],["owner","Owner"],["note","Note"]];
var KEY="ah_lic",ONKEY="ah_lic_on",rows=[],editing=null,today=new Date();today.setHours(0,0,0,0);
function isOn(){try{return localStorage.getItem(ONKEY)==="1"}catch(e){return false}}
function save(){try{if(isOn())localStorage.setItem(KEY,JSON.stringify(rows))}catch(e){}}
function status(t){$("lt-status").textContent=t}
function num(s){var t=String(s||"").replace(/[^\d.,-]/g,"");if(/,\d{1,2}$/.test(t))t=t.replace(/\./g,"").replace(",",".");else t=t.replace(/,/g,"");var n=parseFloat(t);return isNaN(n)?0:n}
function date(s){var m=/^(\d{4})-(\d{1,2})-(\d{1,2})/.exec(String(s||"").trim());if(m)return m[1]+"-"+("0"+m[2]).slice(-2)+"-"+("0"+m[3]).slice(-2);m=/^(\d{1,2})\.(\d{1,2})\.(\d{4})$/.exec(String(s||"").trim());return m?m[3]+"-"+("0"+m[2]).slice(-2)+"-"+("0"+m[1]).slice(-2):""}
function clean(o){return{name:String(o.name||"").trim().slice(0,80),vendor:String(o.vendor||"").trim().slice(0,60),seats:Math.max(0,Math.round(num(o.seats)))||1,price:Math.round(num(o.price)*100)/100,cycle:/^(y|j|ann)/i.test(o.cycle||"")?"yearly":"monthly",renew:date(o.renew),notice:Math.max(0,Math.round(num(o.notice))),owner:String(o.owner||"").trim().slice(0,60),note:String(o.note||"").trim().slice(0,120)}}
function perYear(r){return r.seats*r.price*(r.cycle==="monthly"?12:1)}
function days(s){if(!s)return null;var p=s.split("-");return Math.round((new Date(+p[0],+p[1]-1,+p[2])-today)/864e5)}
function state(r){var d=days(r.renew);if(d===null)return["",""];var cut=d-r.notice;if(d<0)return["out","date has passed: update it"];if(cut<0)return["late","renews in "+d+" days, too late to cancel"];if(cut<=30)return["soon","cancel within "+cut+" days, or it renews"];return["",""]}
function money(n){return Math.round(n).toLocaleString("en-US")}
function render(){var y=0,soon=0,late=0;rows.forEach(function(r){y+=perYear(r);var s=state(r)[0];if(s==="soon")soon++;if(s==="late"||s==="out")late++});
  $("lt-stats").innerHTML='<div class="stats"><div class="stat"><span class="stat-k">subscriptions</span><b class="stat-v" data-raw="1">'+rows.length+'</b></div><div class="stat"><span class="stat-k">per year</span><b class="stat-v" data-raw="1">'+money(y)+'</b><span class="stat-s">'+money(y/12)+' per month</span></div><div class="stat"><span class="stat-k">decide within 30 days</span><b class="stat-v" data-raw="1">'+soon+'</b></div><div class="stat"><span class="stat-k">notice period missed</span><b class="stat-v" data-raw="1">'+late+'</b></div></div>';
  if(!rows.length){out.innerHTML='<p class="dim">Nothing here yet. Add a subscription, import a CSV file, or load the example.</p>';return}
  var list=rows.slice().sort(function(a,b){var x=days(a.renew),z=days(b.renew);return (x===null?9e9:x)-(z===null?9e9:z)});
  var h='<p class="dim asmeta">Sorted by renewal date. Click a name to edit.</p><div class="tw"><table class="tbl astbl"><thead><tr>'+COLS.map(function(c){return '<th scope="col">'+c[1]+'</th>'}).join("")+'<th scope="col">Per year</th></tr></thead><tbody>';
  list.forEach(function(r){var s=state(r),i=rows.indexOf(r);h+='<tr'+(s[0]?' class="as-'+(s[0]==="soon"?"soon":"out")+'"':'')+'><td><button type="button" class="astag" data-edit="'+i+'">'+esc(r.name||"(no name)")+'</button></td><td>'+esc(r.vendor)+'</td><td class="num">'+r.seats+'</td><td class="num">'+r.price.toLocaleString("en-US")+'</td><td>'+r.cycle+'</td><td><span class="asd">'+esc(r.renew)+'</span>'+(s[0]?' <span class="sevtag s-'+(s[0]==="soon"?"med":"high")+'">'+s[1]+'</span>':'')+'</td><td class="num">'+r.notice+'</td><td>'+esc(r.owner)+'</td><td>'+esc(r.note)+'</td><td class="num">'+money(perYear(r))+'</td></tr>'});
  out.innerHTML=h+'</tbody></table></div>'}
(function(){var h="";COLS.forEach(function(c){var id="lt-f-"+c[0];if(c[0]==="cycle")h+='<label>'+c[1]+'<select class="sel" id="'+id+'"><option>monthly</option><option>yearly</option></select></label>';else h+='<label>'+c[1]+'<input class="sel" id="'+id+'" maxlength="120" autocomplete="off" type="'+(c[0]==="renew"?"date":"text")+'"'+(/seats|price|notice/.test(c[0])?' inputmode="decimal"':'')+'></label>'});$("lt-fields").innerHTML=h})();
function openForm(i){editing=i;var r=i===null?{cycle:"yearly",seats:1,notice:30}:rows[i];COLS.forEach(function(c){$("lt-f-"+c[0]).value=r[c[0]]===undefined?"":r[c[0]]});$("lt-del").hidden=i===null;$("lt-form").hidden=false;$("lt-f-name").focus()}
$("lt-add").addEventListener("click",function(){openForm(null)});$("lt-cancel").addEventListener("click",function(){$("lt-form").hidden=true});
$("lt-form").addEventListener("submit",function(e){e.preventDefault();var o={};COLS.forEach(function(c){o[c[0]]=$("lt-f-"+c[0]).value});o=clean(o);if(editing===null)rows.push(o);else rows[editing]=o;save();$("lt-form").hidden=true;status("Saved "+o.name+".");render()});
$("lt-del").addEventListener("click",function(){if(editing===null||!window.confirm("Delete this subscription from the list?"))return;rows.splice(editing,1);save();$("lt-form").hidden=true;render()});
out.addEventListener("click",function(e){var b=e.target.closest("[data-edit]");if(b)openForm(+b.getAttribute("data-edit"))});
function cell(s){s=String(s);if(/^[=+\-@\t\r]/.test(s))s="'"+s;return /[",;\n]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s}
function toCsv(){return COLS.map(function(c){return cell(c[1])}).join(",")+"\r\n"+rows.map(function(r){return COLS.map(function(c){return cell(r[c[0]])}).join(",")}).join("\r\n")+"\r\n"}
function importCsv(t){var L=t.replace(/^﻿/,"").split(/\r?\n/).filter(function(l){return l.trim()}),d=(L[0].match(/;/g)||[]).length>(L[0].match(/,/g)||[]).length?";":/\t/.test(L[0])?"\t":",",n=0;
  function split(l){var o=[],c="",q=false;for(var i=0;i<l.length;i++){var ch=l[i];if(q){if(ch==='"'){if(l[i+1]==='"'){c+='"';i++}else q=false}else c+=ch}else if(ch==='"'&&c==="")q=true;else if(ch===d){o.push(c);c=""}else c+=ch}o.push(c);return o}
  var head=split(L[0]).map(function(h){return h.trim().toLowerCase()}),map={};var A={name:/^(product|name|produkt|lizenz|licen)/,vendor:/^(vendor|hersteller|anbieter)/,seats:/^(seats|anzahl|qty|quantity|menge|users)/,price:/^(price|preis|cost|kosten)/,cycle:/^(billed|cycle|abrechnung|zahl)/,renew:/^(renew|verl|ablauf|expir|end)/,notice:/^(notice|k[uü]nd|frist)/,owner:/^(owner|verantw|besitzer)/,note:/^(note|notiz|bemerk)/};
  head.forEach(function(h,i){Object.keys(A).forEach(function(k){if(map[k]===undefined&&A[k].test(h))map[k]=i})});if(map.name===undefined)return "No column called Product or Name in the first line.";
  L.slice(1,2001).forEach(function(l){var p=split(l),o={};Object.keys(map).forEach(function(k){o[k]=p[map[k]]});o=clean(o);if(o.name){rows.push(o);n++}});save();render();return n+" rows read."}
$("lt-file").addEventListener("change",function(){var f=this.files&&this.files[0];if(!f)return;var rd=new FileReader();rd.onload=function(){status(importCsv(String(rd.result)))};rd.readAsText(f);this.value=""});
$("lt-export").addEventListener("click",function(){if(!rows.length){status("Nothing to export yet.");return}var a=document.createElement("a");a.href="data:text/csv;charset=utf-8,"+encodeURIComponent("﻿"+toCsv());a.download="subscriptions.csv";document.body.appendChild(a);a.click();setTimeout(function(){document.body.removeChild(a)},100);status("Exported "+rows.length+" rows.")});
$("lt-print").addEventListener("click",function(){window.print()});
$("lt-sample").addEventListener("click",function(){function d(n){var x=new Date(today.getTime()+n*864e5);return x.getFullYear()+"-"+("0"+(x.getMonth()+1)).slice(-2)+"-"+("0"+x.getDate()).slice(-2)}
  [["Microsoft 365 Business Premium","Microsoft",25,20.6,"monthly",d(190),30,"IT",""],["Backup software, server","Example Backup",1,890,"yearly",d(41),30,"IT","3-year price ends"],["Firewall security licence","Example Firewall",1,640,"yearly",d(12),90,"IT","ends with the hardware warranty"],["Password manager","Example Vault",25,4,"monthly",d(75),30,"IT",""],["Accounting software","Example Books",3,49,"monthly",d(300),90,"Finance",""],["Domain example.org","Registrar",1,18,"yearly",d(25),0,"IT","auto-renew on: check the card"],["CAD suite","Example CAD",2,2400,"yearly",d(58),60,"Engineering","one seat unused since spring"],["Video meetings","Example Meet",10,13,"monthly",d(-4),30,"Office","nobody knows who ordered it"]].forEach(function(a){var o={};COLS.forEach(function(c,i){o[c[0]]=a[i]});rows.push(clean(o))});save();render();status("Example added.")});
$("lt-clear").addEventListener("click",function(){if(rows.length&&window.confirm("Remove all "+rows.length+" rows?")){rows=[];save();render()}});
$("lt-keep").checked=isOn();$("lt-keep").addEventListener("change",function(){try{if(this.checked){localStorage.setItem(ONKEY,"1");save();status("Kept in this browser, on this device only.")}else{localStorage.removeItem(ONKEY);localStorage.removeItem(KEY);status("Stored copy deleted.")}}catch(e){this.checked=false}});
try{if(isOn()){var s=JSON.parse(localStorage.getItem(KEY)||"[]");if(Array.isArray(s))rows=s.map(clean)}}catch(e){}
render();window.ltTest={rows:function(){return rows},importCsv:importCsv,toCsv:toCsv};
})();
