/* Mail header reader: the route of a message, its delays and its SPF, DKIM and DMARC results, in plain words. */
(function(){"use strict";
var $=function(i){return document.getElementById(i)};
function el(t,c,x){var e=document.createElement(t);if(c)e.className=c;if(x!==undefined&&x!==null)e.textContent=String(x);return e}
function plural(n,w){return n+" "+(n===1?w:w+"s")}
var SEV={crit:0,high:1,med:2,info:3},SEVNAME={crit:"critical",high:"high",med:"medium",info:"info"};
var TLD2={"co.uk":1,"org.uk":1,"ac.uk":1,"gov.uk":1,"com.au":1,"net.au":1,"org.au":1,"co.nz":1,"co.jp":1,"com.br":1,"co.za":1,"com.tr":1,"com.mx":1,"co.in":1,"com.cn":1,"co.at":1,"or.at":1,"com.sg":1,"com.pl":1,"co.il":1,"com.ar":1};
function org(d){d=String(d||"").toLowerCase().replace(/\.$/,"");var p=d.split(".");if(p.length<=2)return d;var l2=p.slice(-2).join(".");return TLD2[l2]?p.slice(-3).join("."):l2}
function addrDomain(s){var m=/<([^>]*)>/.exec(s||"");var a=m?m[1]:String(s||"").trim().split(/\s+/).pop();var at=a.lastIndexOf("@");return at<0?"":a.slice(at+1).replace(/[>\s"']/g,"").toLowerCase()}
function addr(s){var m=/<([^>]*)>/.exec(s||"");return (m?m[1]:String(s||"").trim()).toLowerCase()}
function isPrivate(ip){return /^(10\.|127\.|192\.168\.|169\.254\.|172\.(1[6-9]|2\d|3[01])\.|100\.(6[4-9]|[7-9]\d|1[01]\d|12[0-7])\.|::1$|f[cd][0-9a-f]{2}:|fe80:)/i.test(ip)}
function parseHeaders(text){text=String(text).replace(/\r\n?/g,"\n").replace(/^﻿/,"");
  /* Outlook's dialog and some web mails indent or prefix nothing; a full message ends its header at the first empty line */
  var start=text.search(/^[A-Za-z][A-Za-z0-9-]*:[ \t]?/m);if(start<0)throw new Error("there is no header line in that text. A header looks like \"Received: from ...\" or \"From: ...\"");
  text=text.slice(start);var end=text.search(/\n[ \t]*\n(?![ \t])/);var head=end>=0?text.slice(0,end):text,H=[],cur=null;
  head.split("\n").forEach(function(l){if(/^[ \t]/.test(l)&&cur){cur.v+=" "+l.trim();return}var m=/^([!-9;-~]+):[ \t]?(.*)$/.exec(l);if(m){cur={k:m[1],lk:m[1].toLowerCase(),v:m[2]};H.push(cur)}else if(cur&&l.trim())cur.v+=" "+l.trim()});
  return H}
function decodeWords(s){return String(s||"").replace(/=\?([^?]+)\?([bBqQ])\?([^?]*)\?=(\s+(?==\?))?/g,function(_,cs,enc,txt){try{var bytes;if(enc.toLowerCase()==="b"){var bin=atob(txt.replace(/\s/g,""));bytes=new Uint8Array(bin.length);for(var i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i)}else{var out=[];txt=txt.replace(/_/g," ");for(var j=0;j<txt.length;j++){if(txt[j]==="="&&/^[0-9A-Fa-f]{2}$/.test(txt.substr(j+1,2))){out.push(parseInt(txt.substr(j+1,2),16));j+=2}else out.push(txt.charCodeAt(j)&255)}bytes=new Uint8Array(out)}
      return new TextDecoder(cs.toLowerCase()==="utf8"?"utf-8":cs).decode(bytes)}catch(e){return txt}})}
function parseDate(s){s=String(s||"").replace(/\([^)]*\)/g," ").replace(/\s+/g," ").trim();if(!s)return null;var t=Date.parse(s);if(!isNaN(t))return t;
  var m=/(\d{1,2}) (\w{3}) (\d{4}) (\d{1,2}):(\d{2})(?::(\d{2}))?(?:\.\d+)? ?([+-]\d{4}|[A-Z]{2,4})?/.exec(s);if(!m)return null;var mon="janfebmaraprmayjunjulaugsepoctnovdec".indexOf(m[2].toLowerCase())/3;if(mon<0||mon%1)return null;
  var off=0;if(m[7]&&/^[+-]/.test(m[7]))off=(m[7][0]==="-"?-1:1)*(+m[7].slice(1,3)*60+ +m[7].slice(3));return Date.UTC(+m[3],mon,+m[1],+m[4],+m[5],+(m[6]||0))-off*60000}
function parseReceived(v){var semi=v.lastIndexOf(";"),date=semi>=0?parseDate(v.slice(semi+1)):null,body=semi>=0?v.slice(0,semi):v,r={raw:v,t:date,from:"",by:"",ip:"",helo:"",proto:"",tls:false,id:"",forAddr:""};
  var m=/\bfrom\s+(\S+)/i.exec(body);if(m)r.helo=m[1].replace(/[()]/g,"");
  m=/\bby\s+(\S+)/i.exec(body);if(m)r.by=m[1].replace(/[();]/g,"");
  m=/\bwith\s+([A-Za-z0-9]+(?:\s*\([^)]*\))?)/i.exec(body);if(m)r.proto=m[1].split(/\s/)[0].toUpperCase();if(/with Microsoft SMTP Server/i.test(body))r.proto=/version=TLS/i.test(body)?"ESMTPS":"SMTP";
  m=/\bfor\s+<?([^\s>;]+@[^\s>;]+)>?/i.exec(body);if(m)r.forAddr=m[1];
  m=/\bid\s+(\S+)/i.exec(body);if(m)r.id=m[1];
  var fromPart=/\bfrom\s+(.*?)(?=\s+by\s|$)/i.exec(body);fromPart=fromPart?fromPart[1]:"";
  m=/\[(?:IPv6:)?([0-9a-fA-F:.]{3,45})\]/.exec(fromPart)||/\((?:[^()\s]+\s+)?\[?((?:\d{1,3}\.){3}\d{1,3})\]?\)/.exec(fromPart)||/\b((?:\d{1,3}\.){3}\d{1,3})\b/.exec(fromPart)||/\(([0-9a-fA-F]{1,4}:[0-9a-fA-F:]{4,})\)/.exec(fromPart);if(m)r.ip=m[1];
  m=/\(([a-z0-9][a-z0-9.-]+\.[a-z]{2,})[\s.\[]/i.exec(fromPart);r.rdns=m?m[1].replace(/\.$/,""):"";
  r.from=r.rdns||r.helo||r.ip;
  r.tls=/ESMTPS|ESMTPSA|\bTLS|cipher=|version=TLS/i.test(body)||/^(ESMTPS|ESMTPSA|UTF8SMTPS|UTF8SMTPSA|LMTPS)/.test(r.proto);
  m=/TLS\s?v?_?(1[._][0-3])/i.exec(body);r.tlsv=m?m[1].replace("_","."):"";
  r.local=(/outlook\.com$/i.test(r.helo)&&/outlook\.com$/i.test(r.by))||/^(HTTP|HTTPS|MAPI|LOCAL|LMTP|LMTPS|NNTP)$/.test(r.proto)||/^(localhost|127\.0\.0\.1)$/i.test(r.helo)||(!r.helo&&!r.ip);
  r.auth=/^(ESMTPA|ESMTPSA|UTF8SMTPSA|UTF8SMTPA)$/.test(r.proto);
  return r}
function parseAuthResults(v){var out={srv:"",items:[]},parts=v.split(/;\s*/);if(parts.length&&!/=/.test(parts[0]))out.srv=(parts.shift()||"").trim().split(/\s/)[0];
  parts.forEach(function(p){var m=/^\s*([a-z0-9-]+)\s*=\s*([a-z]+)/i.exec(p);if(!m)return;var it={m:m[1].toLowerCase(),r:m[2].toLowerCase(),props:{},why:""};
    var c=/\(([^)]*)\)/.exec(p);if(c)it.why=c[1];var re=/\b([a-z]+\.[a-z0-9-]+)\s*=\s*("[^"]*"|[^\s;()]+)/gi,x;while((x=re.exec(p)))it.props[x[1].toLowerCase()]=x[2].replace(/^"|"$/g,"");
    var a=/\baction=([a-z]+)/i.exec(p);if(a)it.action=a[1].toLowerCase();var r2=/\breason=(\d+)/i.exec(p);if(r2)it.reason=r2[1];out.items.push(it)});return out}
function kv(v){var o={};String(v).split(";").forEach(function(p){var i=p.indexOf(":");if(i<0)return;o[p.slice(0,i).trim().toLowerCase()]=p.slice(i+1).trim()});return o}
function dur(ms){var s=Math.round(ms/1000),neg=s<0;s=Math.abs(s);var t=s<60?s+" s":s<3600?Math.floor(s/60)+" min "+(s%60?s%60+" s":""):s<86400?Math.floor(s/3600)+" h "+Math.floor(s%3600/60)+" min":Math.floor(s/86400)+" d "+Math.floor(s%86400/3600)+" h";return (neg?"-":"")+t.trim()}
function stamp(t){if(t===null)return "";var d=new Date(t);return d.toISOString().replace("T"," ").slice(0,19)+" UTC"}
function analyse(text){var H=parseHeaders(text),R={H:H,findings:[],hops:[],auth:{},meta:{}};
  function all(k){return H.filter(function(h){return h.lk===k}).map(function(h){return h.v})}
  function one(k){var a=all(k);return a.length?a[0]:""}
  function add(sev,title,why,steps){R.findings.push({sev:sev,title:title,why:why,steps:steps||[]})}
  var rec=all("received");if(!rec.length&&!one("from"))throw new Error("there is no Received or From header in that text");
  var hops=rec.map(parseReceived).reverse();R.hops=hops;
  hops.forEach(function(h,i){h.n=i+1;h.delay=null;if(i>0&&h.t!==null){for(var j=i-1;j>=0;j--)if(hops[j].t!==null){h.delay=h.t-hops[j].t;break}}});
  var M=R.meta;M.from=decodeWords(one("from"));M.to=decodeWords(one("to"));M.subject=decodeWords(one("subject"));M.date=one("date");M.msgid=one("message-id");M.replyTo=decodeWords(one("reply-to"));M.returnPath=one("return-path");
  M.fromDomain=addrDomain(M.from);M.rpDomain=addrDomain(M.returnPath);M.mailer=one("x-mailer")||one("user-agent");M.list=!!(one("list-unsubscribe")||one("list-id"));
  var timed=hops.filter(function(h){return h.t!==null});M.first=timed.length?timed[0].t:null;M.last=timed.length?timed[timed.length-1].t:null;M.total=timed.length>1?M.last-M.first:null;M.sent=parseDate(M.date);
  /* the first server outside the sender's own network */
  var origin=null;hops.forEach(function(h){if(!origin&&h.ip&&!isPrivate(h.ip))origin=h});M.origin=origin;
  /* ---------- authentication ---------- */
  var ars=all("authentication-results").concat(all("arc-authentication-results").map(function(v){return v.replace(/^\s*i=\d+;\s*/,"")})).map(parseAuthResults),A=R.auth;
  ars.forEach(function(ar,idx){ar.items.forEach(function(it){if(["spf","dkim","dmarc","arc","compauth"].indexOf(it.m)<0)return;if(it.m==="dkim"){(A.dkimAll=A.dkimAll||[]).push(it);if(!A.dkim||(A.dkim.r!=="pass"&&it.r==="pass"))A.dkim=it}else if(!A[it.m])A[it.m]=it})});
  M.authSrv=ars.length?ars[0].srv:"";
  var rspf=one("received-spf");if(!A.spf&&rspf){var m=/^\s*([a-z]+)/i.exec(rspf);if(m)A.spf={m:"spf",r:m[1].toLowerCase(),props:{},why:(/\(([^)]*)\)/.exec(rspf)||["",""])[1],fromRecv:true}}
  var sigs=all("dkim-signature").map(function(v){var d=/\bd=([^;\s]+)/.exec(v),s=/\bs=([^;\s]+)/.exec(v),a=/\ba=([^;\s]+)/.exec(v);return{d:d?d[1].toLowerCase():"",s:s?s[1]:"",a:a?a[1]:""}});M.sigs=sigs;
  var spfDom=(A.spf&&(A.spf.props["smtp.mailfrom"]||A.spf.props["smtp.helo"]))||M.rpDomain;if(spfDom&&spfDom.indexOf("@")>=0)spfDom=spfDom.split("@").pop();M.spfDomain=(spfDom||"").toLowerCase();
  var dkimDom=A.dkim?(A.dkim.props["header.d"]||(A.dkim.props["header.i"]||"").replace(/^.*@/,"")):"";if(!dkimDom&&sigs.length)dkimDom=sigs[0].d;M.dkimDomain=(dkimDom||"").toLowerCase();
  var fo=org(M.fromDomain);M.spfAligned=!!(A.spf&&A.spf.r==="pass"&&M.spfDomain&&org(M.spfDomain)===fo);
  M.dkimAligned=!!(A.dkimAll||[]).filter(function(it){var d=(it.props["header.d"]||(it.props["header.i"]||"").replace(/^.*@/,"")).toLowerCase();return it.r==="pass"&&d&&org(d)===fo}).length;
  if(!ars.length&&!rspf)add("info","No authentication results in these headers","The receiving server writes the result of its SPF, DKIM and DMARC checks into a header called Authentication-Results. These headers have none, so either the message never left the sender's own system, or the receiving server does not record its checks, or the header was cut off when copying.",["Copy the headers from the recipient's mailbox, not from the sender's Sent folder.","In Outlook: open the message, File, Properties, and copy all of \"Internet headers\". In Gmail: the three dots, \"Show original\"."]);
  else{
    if(A.dmarc){var dr=A.dmarc.r;
      if(dr==="fail")add(A.dmarc.action&&A.dmarc.action!=="none"?"crit":"high","DMARC failed for "+(A.dmarc.props["header.from"]||M.fromDomain),"Neither SPF nor DKIM passed for a domain that matches the visible From address ("+M.fromDomain+"). That is what a forged sender looks like, and also what a badly set-up legitimate sender looks like."+(A.dmarc.action?" The receiving server's action: "+A.dmarc.action+".":""),
        [M.spfAligned||M.dkimAligned||org(M.spfDomain)===fo||org(M.dkimDomain)===fo?"":"SPF checked "+(M.spfDomain||"an unknown domain")+" and DKIM signed as "+(M.dkimDomain||"nobody")+". One of the two must be "+fo+" or a subdomain of it.","If this is your own domain: add the sending service to your SPF record, and switch on DKIM signing with your domain in that service. The domain check on this site shows your current records.","If you are the recipient and do not expect this message: treat it as forged. Do not click, report it."].filter(Boolean));
      else if(dr==="pass")add("info","DMARC passed","The message is authenticated for "+M.fromDomain+" through "+(M.dkimAligned&&M.spfAligned?"SPF and DKIM":M.dkimAligned?"DKIM":"SPF")+". That proves the domain, not the honesty of whoever uses it: look-alike domains pass DMARC too.");
      else if(dr==="bestguesspass"||dr==="none")add("med",M.fromDomain+" has no DMARC policy","The sender's domain publishes no DMARC record"+(dr==="bestguesspass"?", and Microsoft 365 guessed that the message would have passed":"")+". Anyone can put this domain into a From address, and receivers have no instruction to refuse it.",["If it is your domain: publish a DMARC record, starting with p=none and a report address, then tighten it. See the DMARC report reader."]);
      else add("med","DMARC result: "+dr,"The receiving server could not evaluate DMARC cleanly"+(A.dmarc.why?" ("+A.dmarc.why+")":"")+". temperror and permerror usually mean a DNS problem or a broken record at the sender's domain.")}
    if(A.spf){var sr=A.spf.r;
      if(sr==="fail"||sr==="softfail")add(A.dmarc&&A.dmarc.r==="pass"?"info":sr==="fail"?"high":"med","SPF "+sr+(M.spfDomain?" for "+M.spfDomain:""),"The server that delivered the message ("+(origin?origin.ip:"address unknown")+") is not in the list of servers that "+(M.spfDomain||"the envelope domain")+" allows to send."+(A.dmarc&&A.dmarc.r==="pass"?" DKIM passed, so DMARC still passed: this is normal for forwarded mail and mailing lists.":" Typical causes: a forwarder, a new mail service that was never added to the SPF record, or a forged sender."),
        ["Forwarding breaks SPF by design: the forwarder's server is not in the original sender's record. Only DKIM survives it.","If it is your domain, compare the sending address above with your SPF record."]);
      else if(sr==="pass"&&!M.spfAligned&&M.spfDomain&&M.fromDomain)add("info","SPF passed, but for "+M.spfDomain+", not for "+M.fromDomain,"SPF checks the envelope sender (Return-Path), which the reader never sees. Here that is a different domain than the visible From. This is normal for newsletters and services that send on someone's behalf, and it means SPF alone does not authenticate the From address: DKIM has to.");
      else if(sr==="none")add("med","No SPF record for "+(M.spfDomain||"the sending domain"),"The envelope domain publishes no list of allowed servers.",["If it is your domain: publish an SPF record that lists every service that sends for you and ends in -all or ~all."]);
      else if(sr==="temperror"||sr==="permerror")add("med","SPF "+sr,sr==="permerror"?"The SPF record of "+(M.spfDomain||"the sender")+" is broken: a syntax error, two SPF records, or more than ten DNS lookups. Receivers treat that differently, some as a fail.":"A DNS lookup failed while checking SPF. If it happens repeatedly, the sender's DNS is unreliable.")}
    if(A.dkim){if(A.dkim.r==="fail"||A.dkim.r==="permerror")add(A.dmarc&&A.dmarc.r==="pass"?"info":"med","DKIM "+A.dkim.r+(M.dkimDomain?" for "+M.dkimDomain:""),"The signature did not verify"+(A.dkim.why?" ("+A.dkim.why+")":"")+". Either the message was changed on the way (a mailing list footer, a gateway that rewrites links or adds a disclaimer), or the public key in DNS does not match the signing key.",["\"body hash did not verify\" means the content was changed after signing.","\"no key\" or \"key not found\" means the selector record is missing in DNS: "+(sigs.length?sigs[0].s+"._domainkey."+sigs[0].d:"selector._domainkey.domain")+"."]);
      else if(A.dkim.r==="pass"&&!M.dkimAligned&&M.fromDomain)add("info","DKIM passed, signed by "+M.dkimDomain+", not by "+M.fromDomain,"A valid signature of another domain proves that this service sent the message, not that "+M.fromDomain+" did. For DMARC it does not count. Typical for services where custom DKIM was never set up.",["If it is your domain: switch on DKIM with your own domain in the sending service (two or three CNAME records)."])}
    if((!A.dkim||A.dkim.r==="none")&&!sigs.length&&ars.length)add("med","The message is not DKIM-signed","Without a signature, authentication rests on SPF alone, and SPF breaks at the first forwarder.",["If it is your domain: switch on DKIM signing on your mail server or in your mail service."]);
    if(A.arc&&A.arc.r==="fail")add("info","ARC chain failed","ARC lets forwarders vouch for the checks they made. A failed chain only matters when SPF and DKIM failed too and the receiver would otherwise have trusted the forwarder.");
    if(A.compauth){var cr=A.compauth.reason||"";if(A.compauth.r==="fail")add("high","Microsoft 365: composite authentication failed (reason "+cr+")","Exchange Online combines SPF, DKIM, DMARC and its own sender reputation into one verdict. Fail means it treats the sender as spoofed. Reason 000 is an explicit DMARC fail, 001 an implicit fail (no DMARC record and neither SPF nor DKIM match the From domain).",["For a legitimate sender: fix SPF and DKIM alignment at the sender. An entry in the Tenant Allow/Block List for spoofed senders is the stopgap, not the fix."])}}
  /* ---------- route ---------- */
  var slow=hops.filter(function(h){return h.delay!==null&&h.delay>=300000}),warm=hops.filter(function(h){return h.delay!==null&&h.delay>=30000&&h.delay<300000}),neg=hops.filter(function(h){return h.delay!==null&&h.delay<-5000});
  slow.forEach(function(h){add(h.delay>=3600000?"high":"med","Hop "+h.n+" took "+dur(h.delay)+": "+(h.by||"unknown server"),"The message arrived at "+(h.by||"this server")+" "+dur(h.delay)+" after the server before it had it. The wait happened between the two: in the sending server's queue, or because "+(h.by||"the receiver")+" refused it at first.",["Greylisting delays a first message from a new sender by 5 to 30 minutes on purpose. A second message from the same sender is fast.","A scanner or sandbox (attachment detonation) holds mail for several minutes.","Hours mean a queue: the receiving server was unreachable or deferred with a 4xx code. The sending server's log has the reason.","Ask the admin of "+(hops[h.n-2]&&hops[h.n-2].by||"the sending server")+" for the queue log of that time: "+stamp(h.t)+"."])});
  if(neg.length)add("info","A server clock is wrong",neg.map(function(h){return (h.by||"hop "+h.n)+" is "+dur(-h.delay)+" behind the server before it"}).join("; ")+". The message cannot arrive before it was sent, so one of the two clocks is off. Delays next to that hop cannot be trusted.",["If it is your server: check its time synchronisation."]);
  if(M.sent!==null&&M.first!==null&&M.first-M.sent>900000)add("info","Written "+dur(M.first-M.sent)+" before the first server saw it","The Date header is set by the sender's mail program. The gap to the first Received line means the message sat in an outbox, was scheduled, or the sender's clock is wrong. It is not a transport delay.");
  var ext=hops.filter(function(h){return !h.local&&h.ip&&!isPrivate(h.ip)}),plain=ext.filter(function(h){return !h.tls});
  if(plain.length&&ext.length)add(plain.length===ext.length?"med":"info",plural(plain.length,"hop")+" across the internet without a sign of TLS",plain.map(function(h){return "hop "+h.n+" to "+(h.by||"?")}).join(", ")+". The Received line does not mention ESMTPS or a TLS version. Either the transfer was unencrypted, or the server does not write it down (some do not).",["If your own server is the receiver: check that it offers STARTTLS and logs the protocol."]);
  if(M.replyTo&&M.fromDomain&&addrDomain(M.replyTo)&&org(addrDomain(M.replyTo))!==org(M.fromDomain))add("med","Replies go to another domain","From is "+addr(M.from)+", but a reply would go to "+addr(M.replyTo)+". Newsletters and ticket systems do this legitimately. In a message that asks for money, credentials or a quick favour, it is the classic sign of fraud.");
  if(M.rpDomain&&M.fromDomain&&org(M.rpDomain)!==org(M.fromDomain)&&!M.list&&!(A.dmarc&&A.dmarc.r==="pass"))add("info","Envelope sender and visible sender differ","Return-Path is "+M.rpDomain+", From is "+M.fromDomain+". Bounces go to the first one. Services that send for others do this; so do forgers.");
  var disp=/^\s*"?([^"<]*)"?\s*</.exec(M.from);if(disp&&/@/.test(disp[1])&&addrDomain(disp[1])&&addrDomain(disp[1])!==M.fromDomain)add("high","The display name shows a different address than the real sender","The name part reads \""+disp[1].trim()+"\", the real address is "+addr(M.from)+". Mail programs on phones show only the name. This is done to deceive.");
  /* spam verdicts */
  var far=kv(one("x-forefront-antispam-report")),scl=far.scl!==undefined?far.scl:one("x-ms-exchange-organization-scl");M.scl=scl===""?null:scl;M.far=far;
  if(scl!==""&&scl!==undefined&&scl!==null){var n=parseInt(scl,10);if(n>=5)add("med","Microsoft 365 rated it as spam (SCL "+n+")","SCL 5 and 6 go to Junk, 7 to 9 are high-confidence spam and may be quarantined."+(far.sfv?" Filter verdict "+far.sfv+".":"")+(far.cat?" Category "+far.cat+".":""),["CAT:PHSH or HPHISH means phishing, SPOOF means failed authentication, BULK a newsletter above your bulk threshold.","For a wanted sender, fix the cause shown under authentication first. Allow lists switch off the protection for everything that sender ever sends."]);
    else if(n===-1)add("info","Microsoft 365 skipped spam filtering (SCL -1)","A transport rule, an allowed sender or an internal connector let this message bypass the filter."+(far.sfv?" Verdict "+far.sfv+": "+({SKA:"allowed sender or domain in the anti-spam policy",SKI:"internal message",SKN:"marked safe before filtering, for example by a mail flow rule",SFE:"sender is in the recipient's Safe Senders list",SKB:"blocked by a block list"})[far.sfv.toUpperCase()]+".":""))}
  var ss=one("x-spam-status")||one("x-spam-flag"),sc=one("x-spam-score")||(/score=(-?[\d.]+)/.exec(ss)||["",""])[1];M.spam=ss;if(/^\s*yes/i.test(ss))add("med","The spam filter flagged it"+(sc?" (score "+sc+")":""),"X-Spam-Status says yes. The rule names that follow the score say why: "+(/tests=([^\s]+(?:\s+[A-Z0-9_,]+)*)/.exec(ss)||["","not listed"])[1].slice(0,200)+".");
  if(hops.length>=9)add("info",hops.length+" hops","More stations than usual. Each gateway, filter and forwarder adds one. Look for the same server name twice: that is a loop or a forward back to where it came from.");
  R.findings.sort(function(a,b){return SEV[a.sev]-SEV[b.sev]});R.worst=R.findings.length?R.findings[0].sev:"none";return R}
window.mailHdr={parse:parseHeaders,analyse:analyse,received:parseReceived};
var SAMPLE=["Received: from DB9PR04MB8201.eurprd04.prod.outlook.com (2603:10a6:10:24f::12)"," by AM0PR04MB6883.eurprd04.prod.outlook.com with HTTPS; Tue, 6 Oct 2026 07:52:41 +0000","Received: from AS8PR04CA0101.eurprd04.prod.outlook.com (2603:10a6:20b:31e::16)"," by DB9PR04MB8201.eurprd04.prod.outlook.com (2603:10a6:10:24f::12) with Microsoft SMTP Server (version=TLS1_3,"," cipher=TLS_AES_256_GCM_SHA384) id 15.20.8093.20; Tue, 6 Oct 2026 07:52:39 +0000","Received: from mx-gate2.example-filter.net (198.51.100.44) by"," AM4PEPF00027A63.mail.protection.outlook.com (10.167.16.73) with Microsoft SMTP Server (version=TLS1_2,"," cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id 15.20.8093.17 via Frontend Transport; Tue, 6 Oct 2026 07:52:38 +0000","Authentication-Results: spf=fail (sender IP is 198.51.100.44)"," smtp.mailfrom=billing.example.com; dkim=fail (body hash did not verify)"," header.d=billing.example.com;dmarc=fail action=quarantine"," header.from=billing.example.com;compauth=fail reason=000","Received-SPF: Fail (protection.outlook.com: domain of billing.example.com does not"," designate 198.51.100.44 as permitted sender) receiver=protection.outlook.com;"," client-ip=198.51.100.44; helo=mx-gate2.example-filter.net;","Received: from scan-node7.example-filter.net (scan-node7.example-filter.net [198.51.100.61])","\tby mx-gate2.example-filter.net (Postfix) with ESMTPS id 4XkQ2r1Zz9z4wB","\tfor <nico@example.org>; Tue,  6 Oct 2026 07:52:36 +0000 (UTC)","Received: from mta3.billing.example.com (mta3.billing.example.com [203.0.113.25])","\tby scan-node7.example-filter.net (Postfix) with ESMTP id 4XkPh40Vkrz4w9","\tfor <nico@example.org>; Tue,  6 Oct 2026 07:36:12 +0000 (UTC)","Received: from app-worker-12 (unknown [10.20.4.18])","\tby mta3.billing.example.com (Postfix) with ESMTPA id 9D3F21A0074","\tfor <nico@example.org>; Tue,  6 Oct 2026 09:36:09 +0200 (CEST)","DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=billing.example.com;","\ts=sel2024; t=1791272169; bh=Zk1c2Yw3n0G2v6mJ4xqQ8u5pT1rL7aH9dE0fB3sK6c=;","\th=From:To:Subject:Date:Message-ID; b=Qm9ndXMgc2lnbmF0dXJlIGZvciB0aGUgZXhhbXBsZQ==","From: \"Example Billing\" <invoices@billing.example.com>","To: Nico <nico@example.org>","Reply-To: accounts@example-billing-support.net","Subject: =?UTF-8?Q?Invoice_4471_is_ready_=E2=80=93_please_review?=","Date: Tue, 6 Oct 2026 09:36:08 +0200","Message-ID: <20261006073608.9D3F21A0074@mta3.billing.example.com>","Return-Path: bounce-4471@billing.example.com","X-Mailer: BillingApp 4.2","X-MS-Exchange-Organization-SCL: 5","X-Forefront-Antispam-Report: CIP:198.51.100.44;CTRY:NL;LANG:en;SCL:5;SRV:;IPV:NLI;SFV:SPM;H:mx-gate2.example-filter.net;PTR:mx-gate2.example-filter.net;CAT:SPOOF;SFS:(13230040);DIR:INB;","MIME-Version: 1.0","Content-Type: text/plain; charset=utf-8","","Body text is ignored."].join("\n");
window.mailHdr.sample=SAMPLE;
if(!$("mh-run"))return;
var state={R:null};
function tile(label,value,sub){var d=el("div","stat");d.append(el("span","stat-k",label));var b=el("b","stat-v",value);b.setAttribute("data-raw","1");d.append(b);if(sub)d.append(el("span","stat-s",sub));return d}
function badge(it,label,aligned){var r=it?it.r:"none",cls=r==="pass"?(aligned===false?"mhwarn":"mhpass"):r==="none"||!it?"mhnone":r==="fail"||r==="permerror"?"mhfail":"mhwarn";var d=el("div","mhauth "+cls);d.append(el("span","mhak",label),el("b",null,it?r:"not checked"));return d}
function timeline(R){var hops=R.hops,wrap=el("ol","mhtl"),max=0;hops.forEach(function(h){if(h.delay!==null&&h.delay>max)max=h.delay});
  hops.forEach(function(h){var li=el("li","mhhop"+(h.delay!==null&&h.delay>=300000?" isslow":h.delay!==null&&h.delay>=30000?" iswarm":"")),head=el("div","mhhh");
    head.append(el("span","mhn",String(h.n)),el("b",null,h.by||"(server not named)"));if(h.proto)head.append(el("span","mhproto"+(h.tls?" istls":""),h.proto+(h.tlsv?" TLS "+h.tlsv:h.tls&&!/S/.test(h.proto.slice(-2))?" TLS":"")));
    var meta=el("div","mhmeta");meta.append(el("span",null,"from "+(h.from||"unknown")+(h.ip&&h.from!==h.ip?" ["+h.ip+"]":"")+(h.ip&&isPrivate(h.ip)?" (internal)":"")));if(h.t!==null)meta.append(el("span","mht",stamp(h.t)));
    var bar=el("div","mhbar"),fill=el("i");var w=h.delay===null||h.delay<=0||!max?0:Math.max(2,Math.sqrt(h.delay/max)*100);fill.style.width=w+"%";bar.append(fill);
    var dl=el("span","mhd",h.n===1?"start":h.delay===null?"no time":h.delay<1000&&h.delay>=0?"under 1 s":"+ "+dur(h.delay));
    li.append(head,meta,bar,dl);wrap.append(li)});return wrap}
function render(){var out=$("mh-out"),R=state.R,M=R.meta,A=R.auth;out.replaceChildren();
  $("mh-status").textContent=plural(R.H.length,"header line")+" and "+plural(R.hops.length,"hop")+" read.";
  var real=R.findings.filter(function(f){return f.sev!=="info"}).length,v=el("div","verdict v-"+(R.worst==="none"||R.worst==="info"?"none":R.worst));
  var authOk=A.dmarc&&A.dmarc.r==="pass",authBad=A.dmarc&&A.dmarc.r==="fail";
  v.append(el("b",null,authBad?"Not authenticated":R.worst==="high"||R.worst==="crit"?"Needs a closer look":R.worst==="med"?"Worth a look":authOk?"Authenticated and on time":"Nothing stands out"),el("span",null,(M.total!==null?"delivered in "+dur(M.total)+" through "+plural(R.hops.length,"hop"):plural(R.hops.length,"hop"))+", "+(R.findings.length?plural(R.findings.length,"finding"):"no findings")));out.append(v);
  var s=el("div","stats");s.style.setProperty("--cols","4");var slowest=R.hops.slice().sort(function(a,b){return (b.delay||0)-(a.delay||0)})[0];
  s.append(tile("time on the way",M.total!==null?dur(M.total):"-",M.first!==null?"from "+stamp(M.first):""),tile("hops",String(R.hops.length),slowest&&slowest.delay>=30000?"slowest: hop "+slowest.n+", "+dur(slowest.delay):"no slow hop"),tile("sent from",M.origin?M.origin.ip:"-",M.origin?(M.origin.rdns||M.origin.helo||"")+(M.far&&M.far.ctry?" ("+M.far.ctry+")":""):"no public address in the headers"),tile("spam verdict",M.scl!==null&&M.scl!==undefined?"SCL "+M.scl:M.spam?(/^\s*yes/i.test(M.spam)?"flagged":"clean"):"-",M.far&&M.far.cat?"category "+M.far.cat:M.far&&M.far.sfv?"verdict "+M.far.sfv:""));out.append(s);
  out.append(el("h2",null,"who it claims to be from"));
  var dl=el("dl","mhdl");function row(k,val,cls){if(!val)return;dl.append(el("dt",null,k));var dd=el("dd",cls||null,val);dl.append(dd)}
  row("From",M.from);row("Reply-To",M.replyTo,M.replyTo&&org(addrDomain(M.replyTo))!==org(M.fromDomain)?"mhodd":null);row("Return-Path",M.returnPath,M.rpDomain&&org(M.rpDomain)!==org(M.fromDomain)?"mhodd":null);row("To",M.to);row("Subject",M.subject);row("Date",M.date);row("Message-ID",M.msgid);row("Sent with",M.mailer);out.append(dl);
  out.append(el("h2",null,"authentication"));var au=el("div","mhauths");
  au.append(badge(A.spf,"SPF"+(M.spfDomain?" for "+M.spfDomain:""),A.spf&&A.spf.r==="pass"?M.spfAligned:undefined),badge(A.dkim,"DKIM"+(M.dkimDomain?" by "+M.dkimDomain:""),A.dkim&&A.dkim.r==="pass"?M.dkimAligned:undefined),badge(A.dmarc,"DMARC for "+(M.fromDomain||"the From domain")));if(A.arc)au.append(badge(A.arc,"ARC"));if(A.compauth)au.append(badge(A.compauth,"Microsoft composite"));out.append(au);
  out.append(el("p","dim mhnote","SPF and DKIM only count for DMARC when their domain matches the From domain ("+(M.fromDomain||"unknown")+"). Amber means: passed, but for another domain."+(M.authSrv?" Checked by "+M.authSrv+".":"")));
  out.append(el("h2",null,"the route, oldest first"));out.append(el("p","dim","Each server adds one Received line on top. Read from the bottom they tell the journey. The bar shows the wait before that hop."));out.append(timeline(R));
  out.append(el("h2",null,"findings"));if(!R.findings.length)out.append(el("p","dim","Nothing unusual: authenticated, no slow hop, no mismatch between the visible and the real sender."));
  R.findings.forEach(function(f,i){var d=el("details","finding f-"+f.sev);if(i<3&&SEV[f.sev]<=1)d.open=true;var sm=el("summary");sm.append(el("span","sevtag s-"+f.sev,SEVNAME[f.sev]),el("b",null,f.title));d.append(sm,el("p",null,f.why));if(f.steps.length){d.append(el("h3","fh","what to do"));var ol=el("ol","steps");f.steps.forEach(function(x){ol.append(el("li",null,x))});d.append(ol)}out.append(d)});
  var det=el("details","mhall"),sm2=el("summary",null,"All "+R.H.length+" header lines");det.append(sm2);var tw=el("div","tw"),tb=el("table","tbl mhtbl"),body=el("tbody");R.H.forEach(function(h){var tr=el("tr");tr.append(el("th",null,h.k),el("td",null,h.lk==="subject"||h.lk==="from"||h.lk==="to"?decodeWords(h.v):h.v));body.append(tr)});tb.append(body);tw.append(tb);det.append(tw);out.append(det);
  var ctl=el("div","ctl");ctl.style.marginTop="28px";var pr=el("button","btn ghost","Print / save as PDF");pr.type="button";pr.addEventListener("click",function(){document.querySelectorAll("#mh-out details").forEach(function(x){x.open=true});window.print()});ctl.append(pr);out.append(ctl);out.hidden=false;
  var toc=document.querySelector(".tocres");if(toc)toc.hidden=false}
function load(text){try{state.R=analyse(text);render();$("mh-out").scrollIntoView({behavior:"smooth",block:"start"})}catch(e){$("mh-out").hidden=true;$("mh-status").textContent="Could not read that: "+e.message+".";if(!/^there is no/.test(e.message)&&window.console)console.error(e)}}
function readFile(f){if(!f)return;if(f.size>2e7){$("mh-status").textContent="That file is larger than 20 MB. Paste only the headers.";return}var r=new FileReader();r.onload=function(){var t=String(r.result);$("mh-text").value=t.slice(0,60000);load(t)};r.readAsText(f.slice(0,400000))}
var drop=$("mh-drop"),file=$("mh-file");
file.addEventListener("change",function(){readFile(file.files[0]);file.value=""});
["dragenter","dragover"].forEach(function(x){drop.addEventListener(x,function(e){e.preventDefault();drop.classList.add("over")})});
["dragleave","drop"].forEach(function(x){drop.addEventListener(x,function(e){e.preventDefault();drop.classList.remove("over")})});
drop.addEventListener("drop",function(e){if(e.dataTransfer&&e.dataTransfer.files[0])readFile(e.dataTransfer.files[0])});
$("mh-run").addEventListener("click",function(){var t=$("mh-text").value;if(t.trim())load(t);else $("mh-status").textContent="Paste the headers first, or drop the .eml file."});
$("mh-sample").addEventListener("click",function(){$("mh-text").value=SAMPLE;load(SAMPLE)});
if(location.hash==="#sample"){$("mh-text").value=SAMPLE;load(SAMPLE)}
})();
