/* Packet journey: one web request from the PC to the server and back, station by station.
   Break one thing and see where it stops and what the user sees. Then guess the fault from the symptoms. */
(function(){"use strict";
var $=function(i){return document.getElementById(i)};var stage=$("pj-stage");if(!stage)return;
function el(t,c,x){var e=document.createElement(t);if(c)e.className=c;if(x!==undefined&&x!==null)e.textContent=String(x);return e}
function esc(s){return String(s).replace(/[&<>"]/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]})}
var N={pc:{x:70,y:150,l:"PC",s:"10.87.20.14"},sw:{x:230,y:150,l:"Switch",s:"VLAN 20"},gw:{x:400,y:150,l:"Router and firewall",s:"10.87.20.1"},dns:{x:400,y:44,l:"DNS resolver",s:"10.87.10.5"},net:{x:570,y:150,l:"Internet",s:"about 9 routers"},srv:{x:740,y:150,l:"Web server",s:"198.51.100.80"}};
var MAC={pc:"52:54:00:aa:14:01",gw:"52:54:00:fe:00:01",isp:"00:1c:73:10:20:30",srv:"0c:c4:7a:80:80:80"};
/* each station: where the packet is, what happens, the headers as they are now, and how to see it yourself */
var ST=[
{id:"name",at:"pc",to:"dns",t:"A name is not an address",d:"The browser has a name, shop.example.org. Packets need a number. The PC looks in its own cache and hosts file, finds nothing, and asks the DNS server it was given by DHCP.",
 h:{l2:[MAC.pc,MAC.gw],ip:["10.87.20.14","10.87.10.5"],ttl:128,l4:"UDP 51522 > 53",pay:"DNS query: A shop.example.org ?"},
 w:"nslookup shop.example.org\nipconfig /displaydns",x:"dig shop.example.org\nresolvectl query shop.example.org",
 note:"The resolver sits in another network (10.87.10.x), so even this first question goes through the router: stations 2 to 5 happen for the DNS packet too, in a few milliseconds."},
{id:"answer",at:"dns",to:"pc",t:"The resolver finds the answer",d:"The resolver does not know the name either. It asks a root server, then the .org servers, then the name servers of example.org, and keeps the answer for as long as the record's lifetime (TTL) says.",
 h:{l2:[MAC.gw,MAC.pc],ip:["10.87.10.5","10.87.20.14"],ttl:63,l4:"UDP 53 > 51522",pay:"DNS answer: shop.example.org A 198.51.100.80, TTL 300"},
 w:"Resolve-DnsName shop.example.org",x:"dig +trace shop.example.org",note:"Now the PC knows where to send the real request: 198.51.100.80, port 443."},
{id:"mask",at:"pc",to:"pc",t:"Local or not? The subnet mask decides",d:"The PC compares the target with its own address and mask. 10.87.20.14 with /24 means: everything from 10.87.20.0 to 10.87.20.255 is my own network. 198.51.100.80 is not, so the packet goes to the default gateway, 10.87.20.1.",
 h:{l2:[MAC.pc,"?"],ip:["10.87.20.14","198.51.100.80"],ttl:128,l4:"TCP 49832 > 443 SYN",pay:""},
 w:"ipconfig\nroute print -4",x:"ip addr\nip route get 198.51.100.80",note:"The IP packet is addressed to the server. Only the frame around it will be addressed to the gateway. The PC still needs the gateway's hardware address for that."},
{id:"arp",at:"pc",to:"gw",t:"ARP: who has 10.87.20.1?",d:"The PC shouts into its network: who has 10.87.20.1? Every device in VLAN 20 hears it. The router answers with its MAC address, and the PC keeps it for a few minutes.",
 h:{l2:[MAC.pc,"ff:ff:ff:ff:ff:ff"],ip:["ARP","who has 10.87.20.1? tell 10.87.20.14"],ttl:"",l4:"",pay:"answer: 10.87.20.1 is at "+MAC.gw},
 w:"arp -a\nGet-NetNeighbor -IPAddress 10.87.20.1",x:"ip neigh",note:"ARP never leaves the local network. That is why two devices with the same IP address, or a wrong VLAN, break things at exactly this point."},
{id:"switch",at:"sw",to:"gw",t:"The switch forwards by MAC address",d:"The frame arrives on an access port in VLAN 20. The switch looks the target MAC address up in its table and sends the frame out of the one port where the router lives. It does not look at IP addresses at all.",
 h:{l2:[MAC.pc,MAC.gw],ip:["10.87.20.14","198.51.100.80"],ttl:128,l4:"TCP 49832 > 443 SYN",pay:""},
 w:"# on the switch (Cisco style)\nshow mac address-table vlan 20\nshow interfaces status",x:"# on the switch (Cisco style)\nshow vlan brief\nshow interfaces trunk",note:"On the uplink to the router the frame may carry a VLAN tag (802.1Q) with the number 20, if that link is a trunk."},
{id:"route",at:"gw",to:"gw",t:"The router picks the next hop",d:"The router takes the IP packet out of the frame, looks at the target address and searches its routing table for the most specific match. Nothing fits 198.51.100.80 except the default route, so the packet goes towards the internet provider. The TTL goes down by one.",
 h:{l2:["(frame removed)",""],ip:["10.87.20.14","198.51.100.80"],ttl:127,l4:"TCP 49832 > 443 SYN",pay:""},
 w:"tracert -d 198.51.100.80",x:"traceroute -n 198.51.100.80\nip route   # on a Linux router",note:"Every router on the way does the same: unpack, decide, lower the TTL, pack into a new frame. traceroute works by sending packets whose TTL runs out one hop further each time."},
{id:"fw",at:"gw",to:"gw",t:"The firewall decides",d:"Before the packet may leave, the firewall compares it with its rules, top to bottom, and the first rule that matches wins. \"Clients to internet, TCP 443, allow\" matches. The firewall notes the connection in its state table, so the answer will be let back in without a rule of its own.",
 h:{l2:["(frame removed)",""],ip:["10.87.20.14","198.51.100.80"],ttl:127,l4:"TCP 49832 > 443 SYN",pay:"state: NEW, rule 12 allow"},
 w:"Test-NetConnection 198.51.100.80 -Port 443",x:"nc -vz 198.51.100.80 443\nsudo nft list ruleset   # on a Linux firewall",note:"A firewall that drops says nothing: the client waits and times out. One that rejects answers at once: connection refused. The difference tells you which kind of block you hit."},
{id:"nat",at:"gw",to:"net",t:"NAT swaps the source address",d:"10.87.20.14 is a private address. Nobody on the internet could answer it. The router replaces the source with its own public address and a free port, and writes the pair into its translation table.",
 h:{l2:[MAC.gw,MAC.isp],ip:["203.0.113.10","198.51.100.80"],ttl:127,l4:"TCP 61044 > 443 SYN",pay:"NAT table: 10.87.20.14:49832 = 203.0.113.10:61044"},
 w:"# what the outside sees\ncurl ifconfig.me",x:"sudo conntrack -L | grep 198.51.100.80",note:"From here on, the server and everyone in between see 203.0.113.10. All PCs of the office look like one address."},
{id:"inet",at:"net",to:"srv",t:"Across the internet",d:"Router after router repeats station 6. Each one knows only the next step, learned from its neighbours through BGP. After about nine hops and some 20 milliseconds the packet reaches the network of the server.",
 h:{l2:["(changes at every hop)",""],ip:["203.0.113.10","198.51.100.80"],ttl:118,l4:"TCP 61044 > 443 SYN",pay:""},
 w:"pathping 198.51.100.80",x:"mtr -rwc 20 198.51.100.80",note:"The IP addresses stay the same for the whole trip. The MAC addresses change at every single hop."},
{id:"tcp",at:"srv",to:"pc",t:"TCP: three packets before any data",d:"The server has a program listening on port 443. It answers SYN with SYN-ACK, the PC answers with ACK. Both sides now have sequence numbers and know the other one is there. Only then is data sent.",
 h:{l2:[MAC.srv,"(its router)"],ip:["198.51.100.80","203.0.113.10"],ttl:64,l4:"TCP 443 > 61044 SYN-ACK",pay:""},
 w:"Test-NetConnection shop.example.org -Port 443\nnetstat -ano | findstr :443",x:"ss -tn | grep 443\n# on the server: ss -tlnp | grep :443",note:"On the way back, the office router finds 61044 in its NAT table and rewrites the target to 10.87.20.14:49832. The firewall sees a known connection and lets it in."},
{id:"tls",at:"srv",to:"pc",t:"TLS: prove who you are, then encrypt",d:"The PC says which name it wants (SNI) and which ciphers it knows. The server sends its certificate. The PC checks three things: the name is in it, the date is valid, and it chains up to an authority the PC trusts. Both sides then agree on a key.",
 h:{l2:["",""],ip:["198.51.100.80","203.0.113.10"],ttl:64,l4:"TCP 443 > 61044",pay:"TLS 1.3 ServerHello, Certificate: CN=shop.example.org, valid until 2027-01-14"},
 w:"# PowerShell 7\n(Invoke-WebRequest https://shop.example.org).BaseResponse",x:"openssl s_client -connect shop.example.org:443 -servername shop.example.org </dev/null | openssl x509 -noout -subject -dates",note:"Everything after this is encrypted. A firewall in between sees addresses, ports and the server name, not the content."},
{id:"http",at:"srv",to:"pc",t:"HTTP: the actual request",d:"Now, finally, the browser asks for the page: GET / with the host name. The server answers 200 OK and the HTML. The browser reads it and starts all of this again for every image, script and font, mostly over the same connection.",
 h:{l2:["",""],ip:["198.51.100.80","203.0.113.10"],ttl:64,l4:"TCP 443 > 61044",pay:"(encrypted) HTTP/2 200, content-type: text/html"},
 w:"curl.exe -I https://shop.example.org",x:"curl -sI https://shop.example.org",note:"From typing the address to the first byte of the page: about 12 packets and 80 milliseconds. Twelve places where it can go wrong, and each one fails in its own way."}];
/* faults: where the journey stops, what the user sees, what the tools say */
var F=[
{id:"dns",t:"The PC has a wrong DNS server",stop:"name",see:"DNS_PROBE_FINISHED_BAD_CONFIG, or the page loads for ten seconds and then: this site can't be reached.",tools:[["ping 198.51.100.80","answers","The network is fine."],["nslookup shop.example.org","DNS request timed out","Nobody answers on the configured server."],["ipconfig /all","DNS Servers: 10.87.20.200","An address where no DNS server runs."]],why:"Everything by name fails, everything by address works. That pair is the signature of DNS.",fix:"Correct the DNS server in the DHCP scope (option 6), then ipconfig /renew."},
{id:"record",t:"The DNS record does not exist",stop:"answer",see:"DNS_PROBE_FINISHED_NXDOMAIN, at once.",tools:[["nslookup shop.example.org","Non-existent domain","The resolver works and says: no such name."],["nslookup example.org","answers","Other names resolve."],["ping 198.51.100.80","answers","The server itself is reachable."]],why:"The answer comes fast and is a clear no. A broken resolver is slow and silent; a missing record is quick and definite.",fix:"Create the record at the DNS host, or fix the typo in the name."},
{id:"mask",t:"The PC has the wrong subnet mask",stop:"mask",see:"The internet works. One internal server does not, and nobody understands why.",tools:[["ipconfig","10.87.20.14 mask 255.255.0.0","The PC believes all of 10.87.x.x is its own network."],["ping 10.87.10.5","Destination host unreachable","It sends ARP for the server instead of using the gateway. Nobody answers."],["ping 198.51.100.80","answers","Addresses outside 10.87 still go to the gateway."]],why:"A mask that is too wide makes the PC look for far-away hosts on its own cable. Local things and the internet work, the networks in between do not.",fix:"Set the mask to 255.255.255.0: by DHCP, never by hand."},
{id:"gw",t:"The default gateway is wrong or missing",stop:"arp",see:"ERR_INTERNET_DISCONNECTED or ERR_ADDRESS_UNREACHABLE. Colleagues in the same room are reachable, nothing else is.",tools:[["ping 10.87.20.30","answers","A neighbour in the same network."],["ping 10.87.20.1","answers","The real router is there."],["ipconfig","Default Gateway: 10.87.20.254","An address nobody has. ARP for it stays unanswered."],["ping 198.51.100.80","General failure, or request timed out","No way out."]],why:"Own network yes, everything beyond no. The PC knows where it is and has no door.",fix:"Correct the gateway in the DHCP scope (option 3)."},
{id:"vlan",t:"The switch port is in the wrong VLAN",stop:"switch",see:"The PC shows \"no internet\" and has an address starting with 169.254.",tools:[["ipconfig","169.254.83.7","Self-assigned: no DHCP server answered."],["ping 10.87.20.1","General failure","The PC has no usable address."],["show interfaces status (switch)","Gi1/0/12 connected, VLAN 99","The port is up, in a VLAN where no DHCP server and no gateway live."]],why:"Link light on, no address. The cable is fine; the port leads into the wrong network.",fix:"Put the port into VLAN 20: switchport access vlan 20."},
{id:"fw",t:"The firewall drops outgoing 443",stop:"fw",see:"ERR_CONNECTION_TIMED_OUT, after about 20 seconds.",tools:[["nslookup shop.example.org","198.51.100.80","DNS works."],["ping 198.51.100.80","answers","Ping is allowed, so the path exists."],["Test-NetConnection 198.51.100.80 -Port 443","TcpTestSucceeded: False","After a long wait. The SYN was dropped, no answer came."],["tracert","reaches the server","ICMP gets through, TCP 443 does not."]],why:"Ping yes, the port no, and a long wait before the error: something on the way swallows the packets. A closed port on the server would refuse at once.",fix:"Check the firewall log for the drop, then the rule order: the first match wins."},
{id:"nat",t:"NAT is missing for this network",stop:"nat",see:"ERR_CONNECTION_TIMED_OUT. A new VLAN was added last week, and only its PCs are affected.",tools:[["ping 10.87.20.1","answers","The gateway is fine."],["ping 198.51.100.80","Request timed out","Packets leave with the private source address. The answer has nowhere to go."],["tracert -d 198.51.100.80","hop 1 answers, then stars","It dies right after your own router."],["packet capture on the WAN port","source 10.87.20.14","The proof: a private address on the public side."]],why:"Inside works, the first hop answers, nothing after it does. And only one network is affected: the one that was forgotten in the NAT rule.",fix:"Add the network to the outbound NAT (masquerade) rule."},
{id:"closed",t:"The web server program is not running",stop:"tcp",see:"ERR_CONNECTION_REFUSED, immediately.",tools:[["ping 198.51.100.80","answers","The machine is up."],["Test-NetConnection 198.51.100.80 -Port 443","TcpTestSucceeded: False","At once: the server answered the SYN with a reset."],["on the server: ss -tlnp | grep :443","(nothing)","No program listens on 443."],["on the server: systemctl status nginx","failed","There it is."]],why:"Refused and fast means the packet arrived and the machine itself said no. The network did its job.",fix:"On the server: read the service log, fix it, start it. The Linux playground has exactly this case."},
{id:"cert",t:"The certificate has expired",stop:"tls",see:"Your connection is not private. NET::ERR_CERT_DATE_INVALID.",tools:[["Test-NetConnection shop.example.org -Port 443","TcpTestSucceeded: True","Network and port are fine."],["openssl s_client ... | openssl x509 -noout -dates","notAfter=Oct  1 2026","Five days ago."],["curl -I https://shop.example.org","certificate has expired","The same from the command line."]],why:"The connection is made and then refused by the browser, with a message that names the certificate. Not a network problem at all.",fix:"Renew the certificate and reload the web server. Then find out why the renewal did not run."},
{id:"mtu",t:"Large packets vanish on the way (MTU)",stop:"http",see:"The page starts to load and hangs. Small pages work, large downloads and some sites never finish. Often only over the VPN.",tools:[["ping 198.51.100.80","answers","Small packets pass."],["ping -f -l 1472 198.51.100.80","Packet needs to be fragmented but DF set, or no answer","Full-size packets do not fit through."],["ping -f -l 1400 198.51.100.80","answers","Slightly smaller ones do."],["Test-NetConnection -Port 443","True","The handshake uses small packets and works."]],why:"Connecting works, transferring does not. A tunnel on the way has a smaller packet size, and the message that would tell the sender is blocked.",fix:"Allow ICMP \"fragmentation needed\" through the firewalls, or clamp the TCP segment size on the VPN or PPPoE router."}];
var cur=0,fault=null,KEY="ah_pj",solved={},quiz=null,reduce=window.matchMedia&&matchMedia("(prefers-reduced-motion: reduce)").matches;
try{(JSON.parse(sessionStorage.getItem(KEY)||"[]")||[]).forEach(function(i){solved[i]=1})}catch(e){}
function save(){try{sessionStorage.setItem(KEY,JSON.stringify(Object.keys(solved)))}catch(e){}}
function idx(id){for(var i=0;i<ST.length;i++)if(ST[i].id===id)return i;return 0}
function stopAt(){return fault?idx(fault.stop):ST.length}
function icon(k){return({pc:'<rect x="-20" y="-17" width="40" height="26" rx="2"/><path d="M-9 17h18M0 9v8"/>',sw:'<rect x="-26" y="-9" width="52" height="18" rx="3"/><path d="M-20-3h5v6h-5zM-12-3h5v6h-5zM-4-3h5v6h-5zM4-3h5v6h-5zM12-3h5v6h-5z"/>',gw:'<rect x="-24" y="-12" width="48" height="24" rx="4"/><path d="M-24-4h48M-24 4h48M-8-12v8M8-12v8M0-4v8M-8 4v8M8 4v8"/>',dns:'<rect x="-18" y="-16" width="36" height="14" rx="2"/><rect x="-18" y="2" width="36" height="14" rx="2"/><path d="M-13-9h8M-13 9h8"/>',net:'<path d="M-18 12h34a10 10 0 0 0 2-19.800A14 14 0 0 0-9-12a11 11 0 0 0-9 24z"/>',srv:'<rect x="-18" y="-18" width="36" height="11" rx="2"/><rect x="-18" y="-5.500" width="36" height="11" rx="2"/><rect x="-18" y="7" width="36" height="11" rx="2"/>'})[k]}
function drawStage(){var s=ST[cur],broken=fault&&cur===stopAt(),h='<svg viewBox="0 0 810 220" class="pjsvg" role="img" aria-label="The path from the PC through switch, router and internet to the web server. The packet is at: '+esc(N[s.at].l)+(broken?". The journey stops here.":"")+'">';
  [["pc","sw"],["sw","gw"],["gw","net"],["net","srv"],["gw","dns"]].forEach(function(p){h+='<line class="pjlink" x1="'+N[p[0]].x+'" y1="'+N[p[0]].y+'" x2="'+N[p[1]].x+'" y2="'+N[p[1]].y+'"/>'});
  Object.keys(N).forEach(function(k){var n=N[k],on=k===s.at;h+='<g transform="translate('+n.x+' '+n.y+')"><rect class="pjnode'+(on?(broken?" isbad":" ison"):"")+'" x="-38" y="-28" width="76" height="56" rx="10"/><g class="pjico">'+icon(k)+'</g><text class="pjl" y="46">'+esc(n.l)+'</text><text class="pjs" y="60">'+esc(n.s)+'</text></g>'});
  var a=N[s.at],b=N[s.to],px=a.x,py=a.y-40;
  h+='<g class="pjpkt'+(broken?" isbad":"")+'" id="pj-pkt" transform="translate('+px+' '+py+')"><rect x="-13" y="-9" width="26" height="18" rx="3"/><path d="M-13-9l13 9 13-9"/></g>';
  if(broken)h+='<g transform="translate('+a.x+' '+(a.y-40)+')"><path class="pjx" d="M22-8l14 14M36-8l-14 14"/></g>';
  stage.innerHTML=h+'</svg>';
  if(!broken&&!reduce&&s.to!==s.at){var p=$("pj-pkt"),tx=b.x,ty=b.y-40;if(p&&p.animate)p.animate([{transform:"translate("+px+"px,"+py+"px)"},{transform:"translate("+tx+"px,"+ty+"px)"}],{duration:900,easing:"ease-in-out",fill:"forwards"})}}
function headerTable(s,prev){var rows=[["Frame (layer 2)",s.h.l2[0]?s.h.l2[0]+(s.h.l2[1]?"  >  "+s.h.l2[1]:""):"",prev?prev.h.l2.join():null,s.h.l2.join()],["IP (layer 3)",s.h.ip[0]+"  >  "+s.h.ip[1],prev?prev.h.ip.join():null,s.h.ip.join()],["TTL",String(s.h.ttl),prev?String(prev.h.ttl):null,String(s.h.ttl)],["Transport (layer 4)",s.h.l4,prev?prev.h.l4:null,s.h.l4],["Inside",s.h.pay,prev?prev.h.pay:null,s.h.pay]];
  var t=el("table","tbl pjhdr"),b=el("tbody");rows.forEach(function(r){if(!r[1])return;var tr=el("tr"),ch=r[2]!==null&&r[2]!==r[3];tr.append(el("th",null,r[0]));var td=el("td",ch?"pjch":null,r[1]);if(ch){var sr=el("span","sr"," (changed at this station)");td.append(sr)}tr.append(td);b.append(tr)});t.append(b);var w=el("div","tw");w.append(t);return w}
function render(focus){var s=ST[cur],stop=stopAt(),broken=fault&&cur===stop,body=$("pj-body");drawStage();body.replaceChildren();
  var list=$("pj-list");list.replaceChildren();ST.forEach(function(x,i){var li=el("li"),b=el("button","pjst"+(i===cur?" iscur":"")+(fault&&i===stop?" isbad":"")+(fault&&i>stop?" isoff":""));b.type="button";b.append(el("span","pjn",String(i+1)),el("span",null,x.t));if(i===cur)b.setAttribute("aria-current","step");if(fault&&i>stop){b.disabled=true}b.addEventListener("click",function(){cur=i;render(true)});li.append(b);list.append(li)});
  var h=el("h2","plain",(cur+1)+". "+(broken?"It stops here: "+fault.t:s.t));h.id="pj-title";h.tabIndex=-1;body.append(h);
  if(broken){body.append(el("p","pjsee",fault.see));var lab=el("p","pjk","What the user sees");body.insertBefore(lab,body.lastChild);
    body.append(el("p","pjk","What the tools say"));var t=el("table","tbl pjtools"),tb=el("tbody");fault.tools.forEach(function(r){var tr=el("tr");var c=el("td");c.append(el("code",null,r[0]));tr.append(c,el("td","pjres",r[1]),el("td",null,r[2]));tb.append(tr)});t.append(tb);var w=el("div","tw");w.append(t);body.append(w);
    body.append(el("p","pjk","How to tell"),el("p",null,fault.why),el("p","pjk","The fix"),el("p",null,fault.fix));
    body.append(el("p","dim","Normally this station does the following: "+s.d))}
  else{body.append(el("p",null,s.d));body.append(el("p","pjk","The packet right now"),headerTable(s,cur>0?ST[cur-1]:null));
    if(cur>0)body.append(el("p","dim pjleg","Marked fields changed since the station before."));
    body.append(el("p","pjnote",s.note));
    var d=el("div","pjcmds");[["Windows",s.w],["Linux, macOS or the device",s.x]].forEach(function(c){var box=el("div");box.append(el("p","pjk","See it yourself: "+c[0]),el("pre",null,c[1]));d.append(box)});body.append(d)}
  $("pj-prev").disabled=cur===0;$("pj-next").disabled=cur>=Math.min(stop,ST.length-1);$("pj-pos").textContent="Station "+(cur+1)+" of "+ST.length+(fault?". Broken: "+fault.t.charAt(0).toLowerCase()+fault.t.slice(1)+".":"");
  if(focus)h.focus({preventScroll:true})}
$("pj-prev").addEventListener("click",function(){if(cur>0){cur--;render(true)}});
$("pj-next").addEventListener("click",function(){if(cur<Math.min(stopAt(),ST.length-1)){cur++;render(true)}});
var selF=$("pj-fault");F.forEach(function(f){var o=el("option",null,f.t);o.value=f.id;selF.append(o)});
selF.addEventListener("change",function(){fault=null;F.forEach(function(f){if(f.id===selF.value)fault=f});cur=fault?stopAt():0;render(true)});
document.addEventListener("keydown",function(e){if(e.target&&/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if(!stage.closest(".pj").contains(document.activeElement)&&document.activeElement!==document.body)return;if(e.key==="ArrowRight"){$("pj-next").click()}else if(e.key==="ArrowLeft"){$("pj-prev").click()}});
/* ---------- guess the fault ---------- */
function shuffle(a,seed){a=a.slice();for(var i=a.length-1;i>0;i--){seed=(seed*9301+49297)%233280;var j=Math.floor(seed/233280*(i+1)),x=a[i];a[i]=a[j];a[j]=x}return a}
function quizRender(){var box=$("pj-quiz");box.replaceChildren();var n=Object.keys(solved).length;$("pj-score").textContent=n+" of "+F.length+" solved";$("pj-qbar").style.width=Math.round(n/F.length*100)+"%";
  if(!quiz){var open=F.filter(function(f){return !solved[f.id]});if(!open.length){box.append(el("p","pjdone","All ten found. You can now tell a DNS fault from a firewall drop from a dead service by the symptoms alone, which is most of network troubleshooting."));var again=el("button","btn ghost","Start again");again.type="button";again.addEventListener("click",function(){solved={};save();quizRender()});box.append(again);return}
    var f=open[0],others=shuffle(F.filter(function(x){return x.id!==f.id}),f.t.length*7+n).slice(0,3);quiz={f:f,opts:shuffle(others.concat([f]),f.t.length*13+3),tries:0,shown:1}}
  var f2=quiz.f;box.append(el("p","pjk","Ticket "+(n+1)+": what the user reports"),el("p","pjsee",f2.see));
  box.append(el("p","pjk","What you find"));var t=el("table","tbl pjtools"),tb=el("tbody");f2.tools.slice(0,quiz.shown).forEach(function(r){var tr=el("tr");var c=el("td");c.append(el("code",null,r[0]));tr.append(c,el("td","pjres",r[1]));tb.append(tr)});t.append(tb);var w=el("div","tw");w.append(t);box.append(w);
  if(quiz.shown<f2.tools.length&&!quiz.done){var more=el("button","btn ghost","Run another check");more.type="button";more.addEventListener("click",function(){quiz.shown++;quizRender();var b=$("pj-quiz").querySelector(".pjopt");if(b)b.focus()});box.append(more)}
  var fs=el("div","pjopts");fs.setAttribute("role","group");fs.setAttribute("aria-label","What is broken?");quiz.opts.forEach(function(o){var b=el("button","pjopt"+(quiz.wrong&&quiz.wrong[o.id]?" iswrong":"")+(quiz.done&&o.id===f2.id?" isright":""),o.t);b.type="button";if(quiz.done||(quiz.wrong&&quiz.wrong[o.id]))b.disabled=true;
    b.addEventListener("click",function(){if(o.id===f2.id){quiz.done=true;solved[f2.id]=1;save();quizRender();var nx=$("pj-qnext");if(nx)nx.focus()}else{quiz.tries++;quiz.wrong=quiz.wrong||{};quiz.wrong[o.id]=1;quiz.msg="Not that one. With "+o.t.charAt(0).toLowerCase()+o.t.slice(1)+", you would see: "+o.see;if(quiz.shown<f2.tools.length)quiz.shown++;quizRender()}});fs.append(b)});box.append(fs);
  var live=el("div");live.setAttribute("aria-live","polite");
  if(quiz.done){live.append(el("p","pjright","Right"+(quiz.tries?", after "+quiz.tries+(quiz.tries===1?" wrong guess":" wrong guesses"):" first time")+". "+f2.why),el("p",null,"The fix: "+f2.fix));var nx2=el("button","btn solid","Next ticket");nx2.type="button";nx2.id="pj-qnext";nx2.addEventListener("click",function(){quiz=null;quizRender()});var see=el("button","btn ghost","Show where it stops");see.type="button";see.addEventListener("click",function(){selF.value=f2.id;fault=f2;cur=stopAt();render(false);stage.scrollIntoView({block:"start"})});var c=el("div","ctl");c.style.marginTop="10px";c.append(nx2,see);live.append(c)}
  else if(quiz.msg)live.append(el("p","pjwrong",quiz.msg));box.append(live)}
render(false);quizRender();
window.pjTest={stations:ST.length,faults:F.map(function(f){return f.id}),answer:function(){return quiz?quiz.f.t:null},solved:function(){return Object.keys(solved)}};
})();
