(function(){
"use strict";
var $=function(i){return document.getElementById(i)};if(!$("ps-sheet"))return;
function el(t,c,x){var e=document.createElement(t);if(c)e.className=c;if(x!==undefined&&x!==null)e.textContent=String(x);return e}
var P=[
 {id:"phishing",k:"Mail",h:"Stop. Think. Then click.",s:"Four signs that a mail is not what it claims to be",r:["It is urgent, and something bad happens if you do not act now.","It wants a password, a code, or a payment.","The sender's address does not match the name, or the link goes somewhere unexpected. Hover before you click.","You did not expect it: an invoice, a parcel, a shared document, a voicemail."],f:"Not sure? Do not click and do not reply. Ask the sender by phone, or forward it to us."},
 {id:"report",k:"Something odd",h:"Clicked? Tell us. Now.",s:"Nobody gets into trouble for reporting. The trouble starts when we find out three days later.",r:["You entered your password on a page you now doubt.","You opened an attachment and nothing happened, or something strange did.","Your computer behaves differently: windows that pop up, files you cannot open, a mouse that moves.","You approved a sign-in request you did not start."],f:"Leave the computer on, pull the network cable or switch off Wi-Fi, and call."},
 {id:"passwords",k:"Passwords",h:"One password per account. Let the manager remember.",s:"A password used twice is a password already lost",r:["Use the password manager for everything. You remember one long passphrase, it remembers the rest.","Long beats clever: four random words are stronger than P@ssw0rd!23.","Never type your work password into anything you reached through a link.","Nobody from IT will ever ask for your password. Not by mail, not by phone, not in person."],f:"Think a password got out? Change it at once and tell us."},
 {id:"mfa",k:"Sign-in",h:"Only approve what you started.",s:"A sign-in request you did not trigger means someone has your password",r:["A prompt on your phone while you are not signing in: tap Deny.","Read the number or the location on the prompt before you approve.","Never read a code to someone on the phone, whoever they say they are.","Repeated prompts at night are an attack, not a fault. Deny, and tell us in the morning."],f:"Denied a prompt you did not start? Good. Now change your password and tell us."},
 {id:"lock",k:"Your desk",h:"Leaving your desk? Lock your screen.",s:"It takes one second, and one minute is enough for someone else",r:["Windows: the Windows key and L. Mac: Control, Command and Q.","Phones and tablets lock themselves, with a PIN of six digits or more.","Do not leave notebooks in the car, not even in the boot.","Visitors are accompanied. If you do not know someone in the office, ask who they are looking for."],f:""},
 {id:"payment",k:"Money",h:"New bank details? Call back first.",s:"The most expensive mail is the one that changes an account number",r:["A supplier announces new bank details by mail: call them on the number you already have, not the one in the mail.","The boss needs an urgent, confidential transfer, and cannot be reached by phone: that is the scam.","Gift cards as payment are always fraud.","Two people approve every payment above the agreed limit. No exceptions for urgency."],f:"Already paid? Tell accounting and the bank within the hour. Transfers can sometimes be stopped."},
 {id:"usb",k:"Devices",h:"Found a USB stick? Hand it in.",s:"What you plug in becomes part of our network",r:["Unknown sticks, cables and chargers do not go into company computers.","Do not charge your phone on the PC of a hotel, a train or a conference. Use your own charger.","Private devices use the guest Wi-Fi.","Need to move a large file? Ask us for the approved way."],f:""},
 {id:"travel",k:"On the road",h:"Working on the road",s:"A café is not an office",r:["Use the VPN on every network that is not ours. Better still, use your phone's hotspot.","Sit with your back to the wall, or use a privacy screen. Phone calls about customers do not belong on the train.","Never let the notebook out of your sight. At security checks, it goes into the tray last and comes out first.","Lost or stolen? Report it the same day, at any hour. We can lock and wipe it."],f:""},
 {id:"ai",k:"AI tools",h:"Do not paste secrets into a chatbot.",s:"What you type into a public AI service has left the company",r:["No customer data, no personal data, no passwords, no contracts, no source code in tools we have not approved.","Use the AI tools the company provides: they are covered by a contract.","Check what it tells you. It can be confidently wrong.","A voice or a video can be faked. A call from the boss asking for money gets a call back."],f:"Not sure whether a tool is approved? Ask before you use it."},
 {id:"updates",k:"Updates",h:"Restart when it asks.",s:"Most attacks use holes that were fixed months ago, on machines that were never restarted",r:["Updates install in the background and finish with a restart. Do it the same day.","Shut down properly at the end of the week. Closing the lid is not a restart.","Do not install software yourself. Ask us: it takes five minutes.","Phones too: install system updates when they are offered."],f:""}
];
var sel={},list=$("ps-list");
P.forEach(function(p,i){sel[p.id]=i<4;var l=el("label","cschk");var c=el("input");c.type="checkbox";c.checked=sel[p.id];c.addEventListener("change",function(){sel[p.id]=c.checked;render()});l.append(c,document.createTextNode(" "+p.h));list.append(l)});
function render(){var sheet=$("ps-sheet"),contact=$("ps-contact").value.trim(),org=$("ps-org").value.trim(),n=0;sheet.replaceChildren();
  P.forEach(function(p){if(!sel[p.id])return;n++;var a=el("article","poster");a.append(el("p","pk",p.k),el("h2","ph",p.h),el("p","psub",p.s));
    var ol=el("ol","pr");p.r.forEach(function(x){ol.append(el("li",null,x))});a.append(ol);if(p.f)a.append(el("p","pf",p.f));
    var foot=el("p","pc");foot.append(el("b",null,"Questions, or something to report: "),document.createTextNode(contact||"______________________________"));a.append(foot);if(org)a.append(el("p","po",org));sheet.append(a)});
  $("ps-status").textContent=n?n+(n===1?" page":" pages")+" to print, one poster each.":"Choose at least one poster."}
["ps-contact","ps-org"].forEach(function(i){$(i).addEventListener("input",render)});
$("ps-print").addEventListener("click",function(){window.print()});
$("ps-all").addEventListener("click",function(){var on=P.some(function(p){return !sel[p.id]});P.forEach(function(p){sel[p.id]=on});list.querySelectorAll("input").forEach(function(c){c.checked=on});render()});
render();
})();
