(function(){
var $=function(id){return document.getElementById(id)};
if(!$("ob-go"))return;

function copyBtn(btnId,outId){
  var b=$(btnId);if(!b)return;
  b.addEventListener("click",async function(){
    try{await navigator.clipboard.writeText($(outId).textContent);b.textContent="copied";setTimeout(function(){b.textContent="copy"},1200)}
    catch(_){}
  });
}
function psStr(s){return "'"+String(s||"").replace(/'/g,"''")+"'"}

// ---- offboarding ----
function buildOffboard(){
  var upn=$("ob-upn").value.trim()||"user@contoso.com";
  var lines=["# Offboarding script for "+upn,
             "# Generated by admin_hub — review before running.",
             "Connect-MgGraph -Scopes \"User.ReadWrite.All\",\"Directory.ReadWrite.All\",\"Group.ReadWrite.All\"",
             "",
             "$upn = "+psStr(upn),
             "$user = Get-MgUser -UserId $upn"];
  if($("ob-block").checked)lines.push("","# Block sign-in","Update-MgUser -UserId $user.Id -AccountEnabled:$false");
  if($("ob-revoke").checked)lines.push("","# Revoke all refresh tokens and sessions","Revoke-MgUserSignInSession -UserId $user.Id");
  if($("ob-lic").checked)lines.push("","# Remove all assigned licenses","$skus = (Get-MgUserLicenseDetail -UserId $user.Id).SkuId","Set-MgUserLicense -UserId $user.Id -AddLicenses @() -RemoveLicenses $skus");
  if($("ob-groups").checked)lines.push("","# Remove from all Entra ID group memberships","Get-MgUserMemberOf -UserId $user.Id | ForEach-Object {","    Remove-MgGroupMemberByRef -GroupId $_.Id -DirectoryObjectId $user.Id -ErrorAction SilentlyContinue","}");
  if($("ob-gal").checked)lines.push("","# Hide from the global address list (requires Exchange Online module)","# Connect-ExchangeOnline","Set-Mailbox -Identity $upn -HiddenFromAddressListsEnabled $true");
  if($("ob-mailbox").checked)lines.push("","# Convert mailbox to shared (requires Exchange Online module)","# Connect-ExchangeOnline","Set-Mailbox -Identity $upn -Type Shared");
  if($("ob-manager").checked){
    var fwd=$("ob-fwd").value.trim()||"manager@contoso.com";
    lines.push("","# Forward mail to "+fwd+" (requires Exchange Online module)","# Connect-ExchangeOnline","Set-Mailbox -Identity $upn -ForwardingAddress "+psStr(fwd)+" -DeliverToMailboxAndForward $false");
  }
  lines.push("","Write-Host \"Offboarding steps complete for $upn\" -ForegroundColor Green");
  return lines.join("\n");
}
$("ob-go").addEventListener("click",function(){$("ob-out").textContent=buildOffboard()});

// ---- bulk user creation ----
function buildBulk(){
  var raw=$("bk-in").value.trim();
  var loc=($("bk-loc").value.trim()||"DE").toUpperCase();
  if(!raw)return "# Paste at least one line: Display Name,UPN,Password";
  var rows=raw.split("\n").map(function(l){return l.trim()}).filter(Boolean);
  var lines=["# Bulk user creation script",
             "# Generated by admin_hub — review before running.",
             "Connect-MgGraph -Scopes \"User.ReadWrite.All\"",
             "",
             "$users = @("];
  rows.forEach(function(r,i){
    var parts=r.split(",").map(function(x){return x.trim()});
    var name=parts[0]||"User "+(i+1), upn=parts[1]||("user"+(i+1)+"@contoso.com"), pw=parts[2]||"ChangeMe-"+(i+1)+"!";
    lines.push("    @{ DisplayName = "+psStr(name)+"; Upn = "+psStr(upn)+"; Password = "+psStr(pw)+" }"+(i<rows.length-1?"":""));
  });
  lines.push(")","",
    "foreach ($u in $users) {",
    "    $passwordProfile = @{",
    "        Password = $u.Password",
    "        ForceChangePasswordNextSignIn = $true",
    "    }",
    "    $mailNickname = ($u.Upn -split \"@\")[0]",
    "    New-MgUser -DisplayName $u.DisplayName -UserPrincipalName $u.Upn -AccountEnabled `",
    "        -MailNickname $mailNickname -PasswordProfile $passwordProfile -UsageLocation "+psStr(loc),
    "    Write-Host \"Created $($u.Upn)\" -ForegroundColor Green",
    "}");
  return lines.join("\n");
}
$("bk-go").addEventListener("click",function(){$("bk-out").textContent=buildBulk()});

// ---- mailbox permissions ----
function buildMailbox(){
  var target=$("mb-target").value.trim()||"team-shared@contoso.com";
  var grantee=$("mb-grantee").value.trim()||"jane.doe@contoso.com";
  var lines=["# Mailbox permission grant","# Generated by admin_hub — review before running.","Connect-ExchangeOnline","",
             "$target  = "+psStr(target),"$grantee = "+psStr(grantee)];
  if($("mb-full").checked){
    var auto=$("mb-auto").checked;
    lines.push("","# Full Access"+(auto?" (auto-mapped in Outlook)":" (not auto-mapped)"),
      "Add-MailboxPermission -Identity $target -User $grantee -AccessRights FullAccess -InheritanceType All"+(auto?"":" -AutoMapping $false"));
  }
  if($("mb-sendas").checked)lines.push("","# Send As","Add-RecipientPermission -Identity $target -Trustee $grantee -AccessRights SendAs -Confirm:$false");
  if($("mb-sob").checked)lines.push("","# Send on Behalf","Set-Mailbox -Identity $target -GrantSendOnBehalfTo @{Add=$grantee}");
  lines.push("","Write-Host \"Permissions granted on $target for $grantee\" -ForegroundColor Green");
  return lines.join("\n");
}
$("mb-go").addEventListener("click",function(){$("mb-out").textContent=buildMailbox()});

// ---- conditional access ----
function csvToArr(s){return s.split(",").map(function(x){return x.trim()}).filter(Boolean)}
function buildCA(){
  var name=$("ca-name").value.trim()||"New Conditional Access policy";
  var users=csvToArr($("ca-users").value);
  var exclude=csvToArr($("ca-exclude").value);
  var apps=csvToArr($("ca-apps").value);
  var state=$("ca-state").value;
  var grants=[];
  if($("ca-mfa").checked)grants.push('"mfa"');
  if($("ca-compliant").checked)grants.push('"compliantDevice"');
  var lines=["# Conditional Access policy: "+name,
    "# Generated by admin_hub — always create new policies in report-only mode first.",
    "Connect-MgGraph -Scopes \"Policy.ReadWrite.ConditionalAccess\"",
    "",
    "$params = @{",
    "    DisplayName = "+psStr(name),
    "    State       = "+psStr(state),
    "    Conditions  = @{",
    "        Users = @{",
    "            IncludeUsers = @("+(users.length?users.map(psStr).join(", "):'"All"')+")",
    "            ExcludeUsers = @("+(exclude.length?exclude.map(psStr).join(", "):"")+")",
    "        }",
    "        Applications = @{",
    "            IncludeApplications = @("+(apps.length?apps.map(psStr).join(", "):'"All"')+")",
    "        }"];
  if($("ca-legacy").checked)
    lines.push("        ClientAppTypes = @(\"exchangeActiveSync\", \"other\")");
  lines.push("    }");
  if(grants.length){
    lines.push("    GrantControls = @{",
      "        Operator        = \"OR\"",
      "        BuiltInControls = @("+grants.join(", ")+")",
      "    }");
  }
  lines.push("}","","New-MgIdentityConditionalAccessPolicy -BodyParameter $params");
  return lines.join("\n");
}
$("ca-go").addEventListener("click",function(){$("ca-out").textContent=buildCA()});

copyBtn("ob-cp","ob-out");
copyBtn("bk-cp","bk-out");
copyBtn("mb-cp","mb-out");
copyBtn("ca-cp","ca-out");

// seed initial output so the page isn't empty on load
$("ob-out").textContent=buildOffboard();
$("bk-out").textContent="# Paste at least one line above, then click \"generate script\".";
$("mb-out").textContent=buildMailbox();
$("ca-out").textContent=buildCA();

/* ---------- tenant export for the analyzers ---------- */
(function(){
  var out=document.getElementById("ex-out");if(!out)return;
  var days=document.getElementById("ex-days"),ca=document.getElementById("ex-ca"),si=document.getElementById("ex-si");
  function build(){
    var d=Math.min(Math.max(parseInt(days.value,10)||7,1),30),scopes=[],L=[];
    if(ca.checked)scopes.push('"Policy.Read.All"');
    if(si.checked)scopes.push('"AuditLog.Read.All"');
    if(!scopes.length){out.textContent="# Tick at least one export.";return}
    L.push("# Read-only export for the admin_hub analyzers. Writes JSON files into the current folder.","# Requires PowerShell 7 and the Microsoft.Graph module.","","Connect-MgGraph -Scopes "+scopes.join(",")+" -NoWelcome","");
    if(ca.checked)L.push("# Conditional Access policies -> ca-analyzer","Get-MgIdentityConditionalAccessPolicy -All |","    ConvertTo-Json -Depth 10 |","    Out-File ca-policies.json -Encoding utf8","");
    if(si.checked)L.push("# Interactive sign-ins of the last "+d+" day"+(d===1?"":"s")+" -> signin-analyzer",
      '$since = (Get-Date).ToUniversalTime().AddDays(-'+d+').ToString("yyyy-MM-ddTHH:mm:ssZ")',
      'Get-MgAuditLogSignIn -Filter "createdDateTime ge $since" -All |',
      "    Select-Object CreatedDateTime, UserPrincipalName, AppDisplayName, IPAddress, ClientAppUsed, UserAgent, AuthenticationRequirement, Status, Location, DeviceDetail |",
      "    ConvertTo-Json -Depth 6 |","    Out-File signins.json -Encoding utf8","");
    L.push("Disconnect-MgGraph | Out-Null",'Write-Host "Done. Drop the files into the analyzers, then delete them."');
    out.textContent=L.join("\n");
  }
  [days,ca,si].forEach(function(e){e.addEventListener("input",build);e.addEventListener("change",build)});
  document.getElementById("ex-cp").addEventListener("click",function(){var b=this;if(navigator.clipboard)navigator.clipboard.writeText(out.textContent).then(function(){b.textContent="copied";setTimeout(function(){b.textContent="copy"},1200)})});
  build();
})();
})();
