(function(){
"use strict";
var $=function(i){return document.getElementById(i)};
function el(t,c,x){var e=document.createElement(t);if(c)e.className=c;if(x!==undefined&&x!==null)e.textContent=String(x);return e}
/* option: [label, kind (ok|bad|go), title, text, commands, [[link text, href]]] */
var STEPS=[
{id:"load",t:"Is the whole server busy?",why:"The load average counts processes that run or wait for CPU or disk. Compared with the number of cores it tells you whether the machine as a whole is overloaded, or only one thing on it is slow.",
 c:"uptime\nnproc",read:["The three numbers are the average over 1, 5 and 15 minutes.","Divide by the number of cores. Below 0.7 per core is relaxed, around 1 is fully used, above 1 things are waiting.","First number higher than the last: it is getting worse. Lower: the peak is over."],calc:true,
 o:[["Load per core is below 1","ok","The server as a whole is not overloaded","Something specific is slow: one application, the network on the way, name resolution, or the client. Skim steps 2 to 5, then spend your time on steps 6 and 7."],
    ["Above 1 and rising, or steady","go","Overloaded","Something is using up a resource. The next three steps tell you which one: CPU, memory or disk. Keep the terminal open, you will reuse the numbers."],
    ["Above 1 but falling","go","The peak is over","Whatever caused it has finished or was killed. Check steps 3 and 5 for damage, then go to step 8 to find out what ran: a backup, a cron job, an update."]]},
{id:"cpu",t:"Who uses the CPU?",why:"The top line of top splits CPU time by kind. Which kind is high matters more than which process is first.",
 c:"top -bn1 | head -n 15\nps -eo pid,user,pcpu,pmem,etime,comm --sort=-pcpu | head -n 8",read:["us: programs. sy: the kernel. wa: waiting for disk. st: taken away by the hypervisor. id: idle.","In interactive top, press 1 to see each core. One core at 100% and the rest idle is a single-threaded program at its limit."],
 o:[["us is high, one process stands out","bad","One process eats the CPU","Find out what it is and whether it should be running now. A backup, an index rebuild or a virus scan is a scheduling problem. A web worker or a script that spins is a bug: restart it and read its log.","systemctl status PID          # which service the process belongs to\nsudo renice +10 -p PID        # let everything else go first\nsudo systemctl restart NAME"],
    ["wa is high","go","The CPU is waiting for the disk","The processor is idle because the disk is slow. Skip to step 4."],
    ["st is high","bad","The hypervisor is holding you back","Steal time means the virtual machine wanted CPU and the host gave it to someone else. From inside the VM you cannot fix it. On your own host: too many virtual CPUs handed out. At a provider: a noisy neighbour or a burstable instance that ran out of credits. Move the VM or pick a bigger size."],
    ["sy is high","bad","The kernel is busy","Typical causes: a flood of small network packets, a process that forks or opens files in a loop, heavy swapping. Look at context switches and interrupts, then at steps 3 and 6.","vmstat 2 5      # columns in, cs: interrupts and context switches per second\nsudo perf top   # if installed: where the kernel spends its time"],
    ["Mostly idle","ok","CPU is not the problem","Go on."]]},
{id:"mem",t:"Is memory running out?",why:"Linux uses spare memory as file cache, so \"free\" is always small. The column that counts is \"available\". Trouble starts when the server swaps or the kernel kills processes.",
 c:"free -h\nvmstat 2 5\nsudo journalctl -k -b | grep -iE \"out of memory|killed process\" | tail -n 5\nps -eo pid,user,pmem,rss,comm --sort=-rss | head -n 8",read:["free: look at \"available\", not \"free\".","vmstat: the columns si and so are swap in and out per second. Anything other than 0 for several lines means the server is swapping right now."],
 o:[["free is small, available is fine","ok","Normal: the rest is cache","Memory that would otherwise sit unused holds recently read files and is handed back the moment a program needs it. This is the most common false alarm on Linux."],
    ["available is small, si and so are not zero","bad","The server is swapping","Memory is used up and the kernel moves pages to disk and back. Everything becomes slow at once, and the disk looks busy too. Find the largest process. Then either it leaks (restart it, report it), or it is configured larger than the machine (database buffers, Java heap, number of workers), or the server needs more memory.","ps -eo pid,user,pmem,rss,comm --sort=-rss | head\nsystemd-cgtop -m            # memory per service\nsudo systemctl edit NAME    # add under [Service]: MemoryMax=2G"],
    ["The kernel killed processes","bad","Out of memory","The log line names the victim, which is not always the culprit: the kernel kills what frees the most memory. A service that vanishes without an error of its own and comes back later is the usual sign. Limit the greedy service so it is the one that gets stopped, and find out why it grows.","sudo journalctl -k -b | grep -i -B2 -A12 \"out of memory\"\nsystemctl show NAME -p MemoryCurrent,MemoryMax"],
    ["Plenty available, no swapping","ok","Memory is not the problem","Go on."]]},
{id:"io",t:"Is the disk the bottleneck?",why:"A slow disk makes everything wait: the load average climbs while the CPU is idle. This is the most frequent cause on virtual machines and on servers with hard disks.",
 c:"iostat -xz 2 3\nsudo iotop -oPa",read:["iostat comes with the sysstat package. Ignore the first block, it is the average since boot.","%util near 100 means the disk is busy all the time. r_await and w_await are the milliseconds a request takes: single digits on SSD, up to 20 on hard disks is fine.","iotop lists who reads and writes."],
 o:[["%util near 100, await high","bad","The disk cannot keep up","Find the process in iotop. The usual suspects: a backup or a virus scan during working hours, a database query that reads whole tables, a log that floods, or swapping (step 3). Move scheduled jobs to the night and give them low priority. If it is the normal workload, the storage is too slow for it.","sudo ionice -c3 -p PID      # idle priority: only when nobody else wants the disk\nsudo iotop -oPa"],
    ["await high, but %util low","bad","Throttled from outside","The disk is not busy and still answers slowly. On cloud disks that is an IOPS or throughput limit, or burst credits that ran out. On a virtualisation host, another VM is hammering the same storage. On hardware, a degraded RAID or a dying disk.","cat /proc/mdstat\nsudo smartctl -H -A /dev/sda\nsudo dmesg -T | grep -iE \"i/o error|reset|timeout\" | tail"],
    ["Low util, low await","ok","The disk is not the problem","Go on."]],lk:[["Linux disks and LVM cheat sheet","linux-disks-lvm-cheat-sheet.html"]]},
{id:"space",t:"Is a disk full?",why:"A full file system does not slow things down gracefully: databases stop, sessions cannot be written, logins fail. It often looks like \"slow\" from the outside.",
 c:"df -hT\ndf -i\nmount | grep -E \"\\sro[\\s,]\" | grep -v -E \"tmpfs|squashfs|/sys|/proc\"",read:["First command: space. Second: inodes, which run out with millions of small files. Third: file systems that are mounted read-only and should not be."],
 o:[["A file system is at or near 100%","bad","Disk full","Free some space first, then find the cause. The journal, package caches and old logs give quick relief. Then look for what grows.","sudo journalctl --vacuum-time=7d\nsudo du -xh --max-depth=1 / 2>/dev/null | sort -h | tail -n 12\nsudo lsof +L1     # deleted files that still take space"],
    ["Inodes are at 100%","bad","Out of inodes","Space is free, but no new file can be created. Somewhere there are millions of tiny files: PHP sessions, a cache folder, a mail queue. Find the folder with the most entries and clean it up, then fix what fills it.","sudo find / -xdev -type d -size +1M 2>/dev/null | head     # folders with very many entries"],
    ["A file system is read-only","bad","The kernel protected the disk","After I/O errors the kernel remounts a file system read-only. Everything that writes fails. This is a hardware or storage problem until proven otherwise: read the kernel log, check the disk, and make sure you have a backup before you repair anything.","sudo dmesg -T | grep -iE \"i/o error|remount|ext4-fs error|xfs\" | tail -n 20\nsudo smartctl -H -A /dev/sda"],
    ["Enough space everywhere","ok","Space is not the problem","Go on."]],lk:[["Linux disks and LVM cheat sheet","linux-disks-lvm-cheat-sheet.html"]]},
{id:"net",t:"Is it the network or DNS?",why:"A server that waits for a name to resolve looks exactly like a slow server: every first connection takes seconds, then it is fast. Check DNS before anything else on the network.",
 c:"time getent hosts example.org\ncat /etc/resolv.conf\nip -s link\nss -s\nmtr -rwc 20 8.8.8.8",read:["getent should answer in milliseconds. Seconds mean the first DNS server in resolv.conf is dead and each lookup waits for a timeout.","ip -s link: the columns errors and dropped should stay at 0 or not grow.","mtr: loss that starts at one hop and continues to the end is real. Loss at a single hop in the middle is usually just a router that does not answer."],
 o:[["Name lookups take seconds","bad","Slow DNS","The classic. SSH logins that hang for ten seconds, a web app whose first request is slow, mail that queues. Put a working resolver first, and find out why the old one stopped answering.","resolvectl status                 # with systemd-resolved\ndig @192.0.2.53 example.org       # ask one server directly\nsudo nano /etc/resolv.conf        # or the netplan / NetworkManager setting behind it"],
    ["Errors or drops keep growing","bad","A bad link","Cable, switch port, a duplex mismatch or a driver. Check the negotiated speed: a gigabit card running at 100 half duplex is a broken cable or port.","sudo ethtool eth0 | grep -E \"Speed|Duplex|Link detected\"\nsudo dmesg -T | grep -i -E \"eth0|link is\" | tail"],
    ["mtr shows loss on the way","bad","Loss on the path","If the loss starts inside your own network, it is yours to fix. If it starts at the provider, send them the mtr output from both directions."],
    ["A huge number of connections","bad","Flooded, or out of connection slots","Either a real flood from outside or an application that opens connections and never closes them. A full connection tracking table drops new connections silently and logs it.","sudo ss -tn state established | awk '{print $4}' | cut -d: -f1 | sort | uniq -c | sort -rn | head\nsudo dmesg -T | grep -i conntrack | tail"],
    ["All of that looks fine","ok","The network is not the problem","Go on."]]},
{id:"app",t:"Is it the application?",why:"If the machine has resources to spare, the time is lost inside the application or in something it waits for, usually a database or another service.",
 c:"curl -o /dev/null -s -w \"connect %{time_connect}s  first byte %{time_starttransfer}s  total %{time_total}s\\n\" http://127.0.0.1/\nsystemctl status NAME\nsudo journalctl -u NAME --since \"30 min ago\" -p warning --no-pager | tail -n 30",read:["Run curl on the server itself, then the same against the public name from your own machine, and compare.","First byte is the time the application needed to start answering."],
 o:[["Fast on the server, slow from outside","bad","The time is lost in between","A reverse proxy, a load balancer, a firewall that inspects traffic, or the client's own line. Repeat the curl from each hop on the way to find where the seconds appear."],
    ["First byte is slow, even locally","bad","The application or its database","Look at what the application waits for. For a database: the running queries and the slow query log. A missing index on a table that grew is the usual story behind \"it got slower every week\".","mysqladmin processlist\nsudo -u postgres psql -c \"select pid, now()-query_start as running, state, left(query,80) from pg_stat_activity where state <> 'idle' order by 2 desc\""],
    ["The log says workers or connections ran out","bad","A limit was reached","Requests queue up although the machine is idle. Typical log lines: \"server reached pm.max_children\", \"worker_connections are not enough\", \"Too many open files\", \"too many connections\". Raise the limit to what the memory allows, and ask why so many requests are open at once: often something behind them is slow.","sudo systemctl edit NAME     # [Service] LimitNOFILE=65535\ncat /proc/PID/limits"],
    ["The application answers fast","ok","Not the application either","Then compare with a client: is one user slow or all of them, one site or all of them?"]],lk:[["nginx and Apache cheat sheet","nginx-apache-cheat-sheet.html"],["systemd and journalctl cheat sheet","systemd-journalctl-cheat-sheet.html"]]},
{id:"change",t:"What changed?",why:"Servers do not get slow on their own. Something was installed, deployed, scheduled, or grew past a limit. The question \"since when\" is worth more than any tool.",
 c:"last -x reboot shutdown | head -n 5\nsudo journalctl -p warning --since \"3 hours ago\" --no-pager | tail -n 40\ngrep -E \" install | upgrade \" /var/log/dpkg.log | tail -n 15     # Debian, Ubuntu\nsudo dnf history | head -n 12                                    # RHEL, Rocky, Alma\nsystemctl list-timers --all | head -n 15",read:["Line up the time the trouble started with reboots, package updates, deployments and scheduled jobs."],
 o:[["An update or deployment happened right before","bad","A change brought it","Read what the update changed. Roll back if you can, or set the old configuration value: new major versions often change defaults such as worker counts or cache sizes."],
    ["It happens at the same time every day or week","bad","A scheduled job","A backup, a report, log rotation with compression, an antivirus scan, a database dump. Move it out of working hours and lower its priority.","systemctl list-timers --all\nsudo grep -r . /etc/cron.d /etc/crontab 2>/dev/null | grep -v \"^#\"\n# in the job: nice -n 19 ionice -c3 /usr/local/bin/backup.sh"],
    ["Nothing found","go","Collect history for next time","Without numbers from before, every slowdown starts from zero. Install sysstat, which records CPU, memory, disk and network every ten minutes, and you can look back at any point of the last month.","sudo apt install sysstat && sudo systemctl enable --now sysstat\nsar -u -f /var/log/sysstat/sa05     # CPU on the 5th\nsar -d -r -n DEV                    # disk, memory, network today"]]}
];
var picked={};
function copyBtn(text){var b=el("button","btn ghost swcp","copy");b.type="button";b.addEventListener("click",function(){try{navigator.clipboard.writeText(text).then(function(){b.textContent="copied";setTimeout(function(){b.textContent="copy"},1200)})}catch(e){}});return b}
function code(text){var w=el("div","swcode");w.append(el("pre",null,text),copyBtn(text));return w}
function summary(){
  var s=$("sw-sum");s.replaceChildren();var bad=STEPS.filter(function(x){return picked[x.id]!==undefined&&x.o[picked[x.id]][1]==="bad"}),done=Object.keys(picked).length;
  $("sw-prog").textContent=done+" of "+STEPS.length+" steps answered";
  if(!done){s.append(el("p","dim","Answer the steps and your findings collect here."));return}
  var v=el("div","verdict v-"+(bad.length?"high":"none"));v.append(el("b",null,bad.length?(bad.length===1?"One likely cause":bad.length+" likely causes"):"Nothing found so far"),el("span",null,bad.length?"in the order you found them":done<STEPS.length?"keep going":"the server itself looks healthy: compare with a second client and a second network"));s.append(v);
  bad.forEach(function(x){var o=x.o[picked[x.id]],d=el("div","swfound");d.append(el("b",null,o[2]),el("p",null,o[3]));var a=el("a",null,"step "+(STEPS.indexOf(x)+1)+": "+x.t);a.href="#sw-"+x.id;d.append(a);s.append(d)});
}
function build(){
  var host=$("sw-steps");
  STEPS.forEach(function(st,i){
    var sec=el("section","swstep");sec.id="sw-"+st.id;
    var h=el("h2");h.append(el("span","swnum",String(i+1)),document.createTextNode(st.t));sec.append(h,el("p","swwhy",st.why),code(st.c));
    var ul=el("ul","swread");st.read.forEach(function(r){ul.append(el("li",null,r))});sec.append(ul);
    if(st.calc){var c=el("div","swcalc");c.innerHTML='<label>Load, 1 min<input id="sw-l1" class="q" type="text" inputmode="decimal" placeholder="3.20"></label><label>Load, 15 min<input id="sw-l15" class="q" type="text" inputmode="decimal" placeholder="1.10"></label><label>Cores (nproc)<input id="sw-n" class="q" type="text" inputmode="numeric" placeholder="4"></label><p id="sw-lout" aria-live="polite"></p>';sec.append(c)}
    sec.append(el("p","swask","What do you see?"));
    var opts=el("div","swopts"),res=el("div","swres");res.setAttribute("aria-live","polite");
    st.o.forEach(function(o,k){var b=el("button","swopt",o[0]);b.type="button";b.setAttribute("aria-pressed","false");
      b.addEventListener("click",function(){picked[st.id]=k;opts.querySelectorAll("button").forEach(function(x,j){x.classList.toggle("on",j===k);x.setAttribute("aria-pressed",j===k?"true":"false")});
        res.replaceChildren();var card=el("div","swcard k-"+o[1]);card.append(el("b",null,o[2]),el("p",null,o[3]));if(o[4])card.append(code(o[4]));
        if(st.lk&&o[1]==="bad"){var p=el("p","swlk","More: ");st.lk.forEach(function(l,j){var a=el("a",null,l[0]);a.href=l[1];if(j)p.append(document.createTextNode(", "));p.append(a)});card.append(p)}
        if(i<STEPS.length-1){var n=el("a","swnext","next: "+STEPS[i+1].t.toLowerCase().replace(/\?$/,""));n.href="#sw-"+STEPS[i+1].id;card.append(n)}
        res.append(card);sec.classList.remove("s-ok","s-bad","s-go");sec.classList.add("s-"+o[1]);summary()});
      opts.append(b)});
    sec.append(opts,res);host.append(sec);
  });
  var f=function(){var a=parseFloat($("sw-l1").value.replace(",",".")),b=parseFloat($("sw-l15").value.replace(",",".")),n=parseInt($("sw-n").value,10),o=$("sw-lout");
    if(!(a>=0)||!(n>0)){o.textContent="";return}var per=a/n,t=(Math.round(per*100)/100)+" per core: "+(per<0.7?"relaxed.":per<1?"well used, not overloaded.":per<2?"overloaded, things are waiting.":"heavily overloaded: on average "+Math.round(a-n)+" processes are waiting at any moment.");
    if(b>=0)t+=a>b*1.3?" Rising: it started within the last minutes.":a<b*0.7?" Falling: the peak is over.":" Steady for at least a quarter of an hour.";o.textContent=t};
  ["sw-l1","sw-l15","sw-n"].forEach(function(i){$(i).addEventListener("input",f)});
  var first=$("sw-first");if(first)first.after(copyBtn(first.textContent));
  summary();
}
build();
})();
